### ISSUE TITLE
Castle throws exception when disposeing WCF Client that has thrown an MessageSecurityException

### ISSUE THREAD

**Issue by bjo2** [castleproject/Windsor#104]
We have an ASP.NET MVC application with a controller that uses a WCF service. The web application is authenticated by the WCF service using WIF and a Security Token Service (STS). This requires that the WCF service has the STS cert thumbprint in its web.config (<system.identityModel>). 

When a WCF service method is called and the WCF service is configured with a wrong thumbprint the service method throws an exception. In the MVC controller we catch any exceptions thrown by the service since we want to return a response even if there is a problem with the service. 

The controller method returns the ViewResult and Castle Windsor starts cleaning up the controller and its dependencies. However when Windsor disposes the WCF client that threw the MessageSecurityException I get this exception.

This issue was also posted on StackOverflow by an college. Please look this up for more details.

[_Link to issue on StackOverflow_](http://stackoverflow.com/questions/29918066/castle-windsor-throws-a-communicationobjectfaultedexception-when-disposing-a-wcf)

**Comment by jonorossi** [comment]
Fixed by #322.
