### ISSUE TITLE
Castle Windsor and Windows Activities

### ISSUE THREAD

**Issue by Cstolworthy** [castleproject/Windsor#105]
I am using visual studio 2012, and I am targeting .NET 4.5.  I have a project that makes use of windows activities and I was attempting to use Castle Windsor to resolve dependencies for me. However this application is not necessarily hosted in the web. This is code that is shared between a web project and a windows form project.

Create a new console application, add a blank activity to the project and build. The build will pass successfully. Now remove the activity and add Castle Windsor via NuGet, build and it should pass.  Now add a blank activity and attempt to build.  The build will error out with the following message:

Assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' can not be resolved.  Please add a reference to this assembly in the project that is being built.

**Comment by jonorossi** [comment]
That is strange, after a few minutes of digging I found the error is thrown by the `PartialClassGenerationTask` called at `Microsoft.Xaml.targets:L193`.

```
c:\Users\Jonathon\Documents\Visual Studio 2013\Projects\ConsoleApplication1\Activity1.xaml : error XC1014: Assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' can not be resolved.  Please add a reference to this assembly in the project that is being built.
Done executing task "PartialClassGenerationTask" -- FAILED. (TaskId:11)
Done building target "XamlMarkupCompilePass1" in project "ConsoleApplication1.csproj" -- FAILED.: (TargetId:22)
```

I found that I had to add a reference to `System.Web` which Windsor uses (in non client profile builds) and also `System.Drawing` which neither Windsor or Castle Core uses to get it to build.

I had a quick peek inside `PartialClassGenerationTask` and it looks like it gets all references and the references of your references to do some complex magic I didn't dig deep enough to find out.
http://referencesource.microsoft.com/#XamlBuildTask/Microsoft/Build/Tasks/Xaml/PartialClassGenerationTaskInternal.cs,294

Interestingly you can do the same test with a WPF XAML project and it all works, I'm not sure what is different with the WF ones, but it looks like you'll have to just add a reference to the extra assemblies or contact someone that knows more about the internals of WF's XAML build tasks.
