### ISSUE TITLE
register types based on applied attributes

### ISSUE THREAD

**Issue by maurosampietro** [castleproject/Windsor#106]
Is it possible to register types on which an attribute has been applied? 
example:

[FeatureAttribute]
public class Foo : Interface1, Interface2{}

[FeatureAttribute]
public class Foo2 : Interface1, Interface2{}

var regTypes = Types.FromThisAssembly().BasedOn<FeatureAttribute>();
container.Register(regTypes)

**Comment by jonorossi** [comment]
Yes, you can filter using the [`Where` method](https://github.com/castleproject/Windsor/blob/20daf3296f5eb9009d03e12ab4a870268d4b2a0f/src/Castle.Windsor/MicroKernel/Registration/FromDescriptor.cs#L166-L171). I've included the example from the documentation below:

```
Classes.FromAssemblyContaining<MyController>()
    .Where(t => Attribute.IsDefined(t, typeof(CacheAttribute)))
```
https://github.com/castleproject/Windsor/blob/master/docs/registering-components-by-conventions.md
