### ISSUE TITLE
Dependency.DependsOn does not work when registration is done in F#

### ISSUE THREAD

**Issue by luminescent** [castleproject/Windsor#119]
Hi 

Let me start by saying thank you for the wonderful work you put into building this IOC library. It is so great that I have started using it in F#, despite of realizing that this language is not officially supported. Which leads me to coming across an interesting behavior that might merit some interest (and have to admit I have not looked into the Extensibility project which seems to be F# related and could perhaps offer a solution to my issue).

I have a F# project with nuget references to Castle.Core and Castle.Windsor. The code is below: 

```
open Castle.MicroKernel.Registration
open Castle.Windsor

type MyService(myInt: int) = 
    member x.PrintContent = printfn "%A" myInt

[<EntryPoint>]
let main argv =     
    let container = (new WindsorContainer())
                        .Register(Component
                                    .For<MyService>()
                                    .DependsOn(Dependency.OnValue("myInt", 1))) 

    let myService = container.Resolve<MyService>()
    myService.PrintContent

    container.Dispose()

    0 
```

This blows up at run-time, on the resolve line, claiming it cannot find the dependency "myInt" (full stack trace below). The equivalent C# code works flawlessly.

```
Castle.MicroKernel.Handlers.HandlerException was unhandled
Message: An unhandled exception of type 'Castle.MicroKernel.Handlers.HandlerException' occurred in Castle.Windsor.dll
Additional information: Can't create component 'Program+MyService' as it has dependencies to be satisfied.

'Program+MyService' is waiting for the following dependencies:
- Parameter 'myInt' which was not provided. Did you forget to set the dependency?
```

Any help would be greatly appreciated. Thank you.

**Comment by luminescent** [comment]
If anyone encounters this, I managed to figure out how to make it work. Please see below the correction: 
```
    let property: Property = Dependency.OnValue("myInt", 1)
    let container = (new WindsorContainer())
                        .Register(Component
                                    .For<MyService>()
                                    .DependsOn(property)) 
```

What this does is tell Windsor to use this overload from `ComponentRegistration<TService>`: 
```
public ComponentRegistration<TService> DependsOn(Dependency dependency)
```
instead of: 
```
public ComponentRegistration<TService> DependsOn(object dependenciesAsAnonymousType)
```

Using the fluent interface in F# will default to the second overload, which stores the dependency incorrectly internally, thus making it impossible to resolve.

**Comment by luminescent** [comment]
If anyone encounters this, I managed to figure out how to make it work. Please see below the correction: 
```
    let container = 
        (new WindsorContainer())
            .Register(Component
                .For<MyService>()
                .DependsOn(Property.op_Implicit(Dependency.OnValue("myInt", 1)))) 
```

What this does is tell Windsor to use this overload from `ComponentRegistration<TService>`: 
```
public ComponentRegistration<TService> DependsOn(Dependency dependency)
```
instead of: 
```
public ComponentRegistration<TService> DependsOn(object dependenciesAsAnonymousType)
```

F# runtime will not do the implicit cast as C# does and it will default to the second overload, which stores the dependency incorrectly internally, thus making it impossible to resolve.

**Comment by fir3pho3nixx** [comment]
@luminescent - Are you OK to close this issue?

**Comment by luminescent** [comment]
Yes, please, it's just a language issue.

On 21 Sep 2017 16:55, "Gav" <notifications@github.com> wrote:

@luminescent <https://github.com/luminescent> - Are you OK to close this
issue?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/castleproject/Windsor/issues/119#issuecomment-331200716>,
or mute the thread

**Comment by fir3pho3nixx** [comment]
Thanks!
