### ISSUE TITLE
Inline dependencies issue

### ISSUE THREAD

**Issue by bemaxima** [castleproject/Windsor#123]
Hello;

I have a situation like this.
`
static void Main(string[] args)
		{

			
			var container = new Castle.Windsor.WindsorContainer();

			container.Register(
				Component.For<IHigherBusiness>().ImplementedBy<HigherBusiness>().DependsOn(Dependency.OnComponent<ILogger, FullDetailLogger>())
				);

			container.Register(Component.For<ISomeBusiness>().ImplementedBy<Business>());
			container.Register(Component.For<ILogger>().ImplementedBy<FullDetailLogger>().IsFallback());
			container.Register(Component.For<ILogger>().ImplementedBy<SimpleLogger>());

			var business = container.Resolve<IHigherBusiness>();
			business.DoSomething();

			var logger = container.Resolve<ILogger>();
			logger.Log("Some Log... ."); 
			

			
		}
	}

	public interface IHigherBusiness
	{
		void DoSomething();
	}

	public class HigherBusiness : IHigherBusiness
	{
		private ISomeBusiness someBusiness;

		public HigherBusiness(ISomeBusiness someBusiness)
		{
			this.someBusiness = someBusiness;
		}
		public void DoSomething()
		{
			someBusiness.DoSomething();
		}
	}

	public interface ISomeBusiness
	{
		void DoSomething();
	}

	public class Business : ISomeBusiness
	{
		private ILogger logger;
		public Business(ILogger logger)
		{
			this.logger = logger;
		}
		public void DoSomething()
		{
			logger.Log("Message");
		}
	}

	public interface ILogger
	{
		void Log(string message);
	}

	public class SimpleLogger : ILogger
	{

		public void Log(string message)
		{
			Console.WriteLine("Simple Logger: " + message);
		}
	}

	public class FullDetailLogger : ILogger
	{
		public void Log(string message)
		{
			Console.WriteLine("Full detail Logger: " + message);
		}
	}
`
The result is...

> Simple Logger: Message
Simple Logger: Some Log... .

but I expect this

> Full detail Logger:  Message
Simple Logger: Some Log... .

How can I achieve this ?
Thanks in advanced

**Comment by jonorossi** [comment]
This is the Castle Windsor issue tracker, for help with your project please use StackOverflow or our users mailing list as per: http://www.castleproject.org/get-involved/mailing-lists/

I can see you've already logged the question on SO: http://stackoverflow.com/questions/35717276/castle-windsor-inline-dependencies
