### ISSUE TITLE
What is the proper way to call proxied method inside concrete class

### ISSUE THREAD

**Issue by xumix** [castleproject/Windsor#124]
For instance I have IRepository, Implemented by Repository with some Interceptors
Inside the Interceptor I see that IRepositoryProxy basetype is Object and Not the ```Repository```
What I want is to call invocation.Proceed() and all the calls inside to be proxied/intercepted also.
Obviously this does not work since the methods are invoked on the Repository class.

**Comment by jonorossi** [comment]
This is the Castle Windsor issue tracker, for help with your project please use StackOverflow or our users mailing list as per http://www.castleproject.org/get-involved/mailing-lists/.
