### ISSUE TITLE
PerWebRequestLifestyleModule not registered error - when it's registered

### ISSUE THREAD

**Issue by kierenj** [castleproject/Windsor#126]
I get the message,

> A first chance exception of type 'Castle.MicroKernel.ComponentResolutionException' occurred in Castle.Windsor.dll
> 
> Additional information: Looks like you forgot to register the http module Castle.MicroKernel.Lifestyle.PerWebRequestLifestyleModule
> 
> To fix this add
> 
> <add name="PerRequestLifestyle" type="Castle.MicroKernel.Lifestyle.PerWebRequestLifestyleModule, Castle.Windsor" />
> 
> to the <httpModules> section on your web.config.
> 
> Windsor also detected you're running IIS in Integrated Pipeline mode. This means that you also need to add the module to the <modules> section under <system.webServer>.
> 
> Alternatively make sure you have Microsoft.Web.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 assembly in your GAC (it is installed by ASP.NET MVC3 or WebMatrix) and Windsor will be able to register the module automatically without having to add anything to the config file.

However, my web.config has the appropriate line in both `system.web` and `system.webServer` sections.  In addition, the project also directly references `Microsoft.Web.Infrastructure`.

This issue started occurring after I updated many NuGet packages on my project (around 20), as well as updating the targeted .NET version to 4.5.1.

Happy to help diagnose further - not sure what else to try.

**Comment by jonorossi** [comment]
Hi, this is the Castle Windsor issue tracker, for help with your project please use StackOverflow (tagged with `castle-windsor`) or our users mailing list as per http://www.castleproject.org/get-involved/mailing-lists/.

**Comment by jonorossi** [comment]
Looks like you have already done that: http://stackoverflow.com/questions/35969136/windsor-perwebrequestlifestylemodule-registered-but-still-getting-error-messa
