### ISSUE TITLE
Implicit cast converts null to object

### ISSUE THREAD

**Issue by Toxantron** [castleproject/Windsor#127]
In [ServiceOverride.cs L82](https://github.com/castleproject/Windsor/blob/master/src/Castle.Windsor/MicroKernel/Registration/ServiceOverride.cs#L82) the implicit cast converts a ServiceOverride of null into an object. This took me a while to figure out because it is behavior I never saw before. Is this intended?
````c#
public static implicit operator Dependency(ServiceOverride item)
{
    return new Dependency(item);
}
````

I would have expected the cast like this:
````c#
public static implicit operator Dependency(ServiceOverride item)
{
    return item == null ? null : new Dependency(item);
}
````

**Comment by kkozmic** [comment]
Hi @Toxantron good question.
Not sure if that's intended, I think `null` just wasn't considered an option here.

In what scenarios and how were you affected by this?

**Comment by Toxantron** [comment]
First I want to say, that I am impressed by Castle Windsor and we have been using it for years. We even build a C# Application Server with Castle Windsor and a couple of own extensions on top.

We build an attribute based container on top of castle and have a virtual method chain that checks properties for override definitions. In the first version this method returned Dependency and had code like this (I have the code at work, this is as good as I remember):
````c#
protected virtual Dependency DependencyOverride(...)
{
    var namedAttribute = property.GetCustomAttribute<NamedAttribute>();
    return namedAttribute == null ? null : Dependency.On(namedAttribute.Name);
}
````
First confusion was, that Dependency.On does not return a Dependency but a ServiceOverride which was implicitly casted without me noticing it. On the next inheritance level it would check ``c# base.Dependency() `` for null and then look for its own override attributes. However the value was never null. 
One might argue that return null was bad design and bool combined with out preferable. However on a more abstract level this cast has the following affects:
````c#
// Assigning a null ServiceOverride to Dependency creates an object
ServiceOverride a = null;  // a is null
Dependency b = a;           // b is not null

// Explicit cast creates an object as well
Dependency a = (ServiceOverride) null; // Expected to be null but isn't
````

**Comment by Toxantron** [comment]
What do you think? Want to change it or keep it?

**Comment by kkozmic** [comment]
yup, If you're talking about changing it to return `null` when passed `null` as in your first example then yes, it totally makes sense.

**Comment by kkozmic** [comment]
That may also apply to other types of dependencies, not only `ServiceOverride`

**Comment by Toxantron** [comment]
I am gonna do it tonight and open a PR. Alright?

**Comment by Toxantron** [comment]
Will also look for similar code.

**Comment by Toxantron** [comment]
@kkozmic I am currently having trouble with EOL conversions on Linux. I read from the old Castle documentation to turn off autocrlf. I do suppose that was meant for Windows users. However I saw that Windsor comes with a .gitattributes file that overrides these settings anyway. Even though this file instructs git to use CRLF it keeps changing almost every file anyway. 
I am close to just using a WIndows VM but first wanted to ask if this has happend before?

**Comment by Toxantron** [comment]
I kinda managed to work around it. 

1. Removing all eol definitions from .gitattributes
2. ``git reset``
3. ``git checkout *``
4. ``git checkout .gitattributes``

This seems wrong but at least the directory is clean without any commits.

**Comment by Toxantron** [comment]
@jonorossi I give up. I didn't manage to save the files without changing every line ending and it feels like I tried all combinations of ``git config --global core.autocrlf`` with and without _.gitattributes_ file. I am sorry for nur being able to contrbute.

If you find time just search for all occurrences of the cast. There is no need to attribute it to me in any way. Just thought it would be nice if it was fixed.
````c#
public static implicit operator 
````

**Comment by jonorossi** [comment]
@Toxantron I've removed the .gitattributes file, as you worked out that is when the problems started, also we don't have one in Castle Core where we also haven't yet normalised the line endings.

7dc1a89a097d4c0b1122484eaee8ffdde04b45c2 contains the 5 LOC changes.

**Comment by Toxantron** [comment]
Thanks. I will try if I am now able to work on the code. Would love to contribute.
