### ISSUE TITLE
Documentation for PerWebRequest

### ISSUE THREAD

**Issue by altearius** [castleproject/Windsor#133]
The documentation for the `PerWebRequest` life style notes that it is necessary to register the `PerRequestLifestyle` HTTP module to safely use this life style: https://github.com/castleproject/Windsor/blob/master/docs/lifestyles.md

It looks like this has not been necessary since version 3.0.

Perhaps the documentation should be updated to note this.

**Comment by jonorossi** [comment]
@altearius yes, as long as `Microsoft.Web.Infrastructure` is available Windsor's [`PreApplicationStartMethod`](https://github.com/castleproject/Windsor/blob/c7a675659c9a426670c96d9f006f53f056705f67/src/Castle.Windsor/AutoregisterPerWebRequestLifestyleModule.cs) should get called therefore making manually registering the HTTP module unnecessary. Feel free to send through a PR to update the docs, thanks.

**Comment by jonorossi** [comment]
This has been fixed in #320.
