### ISSUE TITLE
Performance Counter Instances Never Removed

### ISSUE THREAD

**Issue by mackenzieajudd** [castleproject/Windsor#146]
We ran into a "Custom counters file view is out of memory" exception in our application running in IIS which brought this issue to light.

We have performance counters enabled as instructed here: https://github.com/castleproject/Windsor/blob/master/docs/performance-counters.md

I found that the TrackedComponentsPerformanceCounterWrapper class never removes the PerformanceCounter instance that it wraps on disposal. If performance counters are enabled for an application which is restarted often the available performance counter memory can be exhausted because a new performance counter, with a unique name, is created every time on startup.

It would be nice if TrackedComponentsPerformanceCounterWrapper removed the wrapped performance counter instance on disposal.

To reproduce:
1. Create a console app with performance counters enabled (https://github.com/castleproject/Windsor/blob/master/docs/performance-counters.md)
2. Start and stop the app multiple times
3. Open Performance Monitor and look at the Castle Windsor category. You should see a performance counter for each time you started the app.

**Comment by jonorossi** [comment]
@mackenzieajudd I'm don't think the intention of the Windsor performance counters was to be used in production always enabled, there shouldn't be any harm though other than this defect obviously. However, won't an application restart cause IIS to tear down the application pool process without really "shutting down" applications resulting in the same outcome?

The code currently calls `PerformanceCounter.Dispose` during clean up, a quick skim of the MSDN docs seems to indicate this is all that is required. What do you mean by remove the performance counter?

Any chance you could provide a pull request with the fix?

**Comment by mackenzieajudd** [comment]
@jonorossi thanks for the quick response!

You may be right about the IIS teardown I'm not sure.

From what I can see `PerformanceCounter.Dispose` releases the resources it is using but won't remove a performance counter from the machine. When you create a new instance of `PerformanceCounter` it will either hook into an existing performance counter if the Category and Name already exist or create a new one if not.

In our case Windsor creates a new performance counter each time because its name is unique (Based on process name and id) to account for multiple instances being tracked at the same time. Because it's not re-using an existing performance counter instance I think the instance should be removed when Windsor is done with it so they don't pile up.

I'll put something together and hopefully have a pull request this week!

I've attached a picture to help illustrate what I'm talking about. The performance counters shown in it have all been created by Windsor but where not removed when the container was disposed and the application was closed.

![multipleperfcounters](https://cloud.githubusercontent.com/assets/3188878/18283728/7da5b366-741b-11e6-8ce0-b3a2cc3727f2.JPG)

**Comment by jonorossi** [comment]
@mackenzieajudd sounds logical to remove the instance on container shutdown, they are obviously pretty useless once the container has shutdown. I'd leave the category around though.

Have you looked at setting `PerformanceCounter.InstanceLifetime = PerformanceCounterInstanceLifetime.Process`, so the counter instances will automatically be removed on process shutdown. After a quick skim it sounds like performance counter instances are built on Windows handles so even if your IIS worker process gets killed the counter instance will get removed because there is no reference to it anymore.

**Comment by jonorossi** [comment]
You'd also have to change the constructor usage of `PerformanceCounter` as most initialize the counter instance which means you can't set the lifetime. Looks like the only one you can use is the no arguments constructor:

http://referencesource.microsoft.com/#System/services/monitoring/system/diagnosticts/PerformanceCounter.cs,7cd5e59dff25918d,references

**Comment by mackenzieajudd** [comment]
Thanks @jonorossi! I opened a pull request fixing this.
