### ISSUE TITLE
Fallback with name can't be overwritten (with same name)

### ISSUE THREAD

**Issue by wdolek** [castleproject/Windsor#147]
Documentation does not state this, but I would expect when something is "fallback", I can override it as I want, including registration name. Unfortunately, this is not true.

Doing this:

```
// base setup
container.Register(Component.For<IDummyService>().ImplementedBy<FallbackService>().Named("LeComponent").IsFallback());

// module setup
container.Register(Component.For<IDummyService>().ImplementedBy<AnotherService>().Named("LeComponent"));
```

Results in exception: "Component LeComponent could not be registered. There is already a component with that name. Did you want to modify the existing component instead? If not, make sure you specify a unique name."

I don't really see way how to overwrite fallback registration including name. Wherever I use registration name, I will always get fallback registration, which is not desired behavior. Either this is bug or I'm missing something.

**Comment by jonorossi** [comment]
You are right the documentation doesn't explicitly mention names when fallback is concerned, however this still applies even if marked fallback: https://github.com/castleproject/Windsor/blob/master/docs/faq.md#can-i-register-more-than-one-component-for-any-given-service

`IsFallback()` really just changes the resolution priority of one component over another, both components are still registered like normal and need a unique name/id which identifies them in the container.

What is your use case where you want them to have the same name?

**Comment by wdolek** [comment]
Main application registers almost everything with name, there could be places, where this name is used for resolution of particular implementation of one interface.

Now, when writing module for this application, I would like to override base registration - which has name assigned. I want to be sure that whatever depends on `IDummyService` and name "LeComponent" is used for resolution, my implementation is picked.

**Comment by sloncho** [comment]
@jonorossi , another use case

This problem has actually a nasty side effect when factory methods are involved, as I guess windsor generates the component name the same way.

So if the original registration is with UsingFactoryMethod and IsFallback, and then later (in tests) the component is re-registered again with factory method, it'll blow and complain about duplicate name.
