### ISSUE TITLE
Problem resolving object with multiple constructors and proxied dependency

### ISSUE THREAD

**Issue by arogg** [castleproject/Windsor#148]
Sample console app (only dep is castle):

```
using System;
using System.IO;
using System.Reflection;
using Castle.DynamicProxy;
using Castle.Facilities.TypedFactory;
using Castle.MicroKernel.Registration;
using Castle.MicroKernel.SubSystems.Configuration;
using Castle.Windsor;

namespace failnpcinterceptor
{
  public interface ITransient
  {
  }

  public interface IViewModel
  {
  }

  public interface INotifyPropertyChangedInterceptor : ITransient, IInterceptor
  {
  }

  public class NotifyPropertyChangedInterceptor : INotifyPropertyChangedInterceptor
  {
    public void Intercept(IInvocation invocation)
    {
      invocation.Proceed();
    }
  }

  public class BaseInstaller : IWindsorInstaller
  {
    public void Install(IWindsorContainer container, IConfigurationStore store)
    {
      var asmFilter = new AssemblyFilter(new Uri(Path.GetDirectoryName(
        Assembly.GetEntryAssembly().CodeBase)).LocalPath);

      container.Register(

        Classes
        .FromAssemblyInDirectory(asmFilter)
        .BasedOn(typeof(ITransient))
        .WithServiceDefaultInterfaces()
        .LifestyleTransient(),

        Classes
        .FromAssemblyInDirectory(asmFilter)
        .BasedOn(typeof(IViewModel))
        .WithServiceDefaultInterfaces()
        .LifestyleTransient()
        // if i comment out the interceptor part, the code WORKS
        .ConfigureFor<IViewModel>(c => c.Interceptors<INotifyPropertyChangedInterceptor>()));
    }
  }

  public interface IMyViewModel : IViewModel
  {
  }

  public class MyViewModel : IMyViewModel
  {
  }

  public interface IMyTransient : ITransient
  {
  }

  public class MyTransient : IMyTransient
  {
    public MyTransient(string name, IMyViewModel vm)
    {
    }

    // OR if i comment out this constructor, the code WORKS
    public MyTransient(int number, IMyViewModel vm)
    {
    }
  }


  public class Program
  {
    static void Main(string[] args)
    {
      var container = new WindsorContainer();
      container.Install(new BaseInstaller());
      // exception here:
      var l = container.Resolve(typeof(IMyTransient), new {name = "mystring"});
    }
  }
}
```

The following exception occurs:

> An unhandled exception of type 'Castle.MicroKernel.Handlers.HandlerException' occurred in Castle.Windsor.dll
> 
> Additional information: Can't create component 'failnpcinterceptor.MyTransient' as it has dependencies to be satisfied.
> 
> 'failnpcinterceptor.MyTransient' is waiting for the following dependencies:
> - Parameter 'name' which was not provided. Did you forget to set the dependency?
> - Service 'failnpcinterceptor.MyViewModel' which was registered but is also waiting for dependencies.
> 
> 'failnpcinterceptor.MyViewModel' is waiting for the following dependencies:
> - Component 'failnpcinterceptor.INotifyPropertyChangedInterceptor' (via override) which was not found. Did you forget to register it or misspelled the name? If the component is registered and override is via type make sure it doesn't have non-default name assigned explicitly or override the dependency via name.
> - Parameter 'number' which was not provided. Did you forget to set the dependency?

If I comment out the second constructor OR the part where the interceptor is added (in the WindsorInstaller), the code works, however.

I suspect this is a bug? Is there a workaround other than using a single constructor with an artificial argument that replaces the multiple constructors?

**Comment by radislavkireev** [comment]
Hi, 

Probably this note is too late, but the problem is in the registration line:
`ConfigureFor<IViewModel>(c => c.Interceptors<INotifyPropertyChangedInterceptor>()));`

There is no link between the  current dependency and implementation, rewrite it as 
`ConfigureFor<IViewModel>(c => c.Interceptors<NotifyPropertyChangedInterceptor>()));`
and the sample will work as expected.

**Comment by jonorossi** [comment]
Thanks @radislavkireev

Hi @arogg, this is the Castle Windsor issue tracker, for help with your project please use [StackOverflow](http://stackoverflow.com/) (tagged with `castle-windsor`) or our users mailing list as per http://www.castleproject.org/get-involved/mailing-lists/.
