### ISSUE TITLE
castle.per-web-request-lifestyle-cache is missing from HttpContext.Items when the client is IE.

### ISSUE THREAD

**Issue by Tilerphy** [castleproject/Windsor#152]
Hi Team,

As the title said, I find that the **castle.per-web-request-lifestyle-cache** is missing. I can find it when visit the controller via Chrome and Firefox.

I didn't write this in web.config:

**<add name="PerRequestLifestyle" type="Castle.MicroKernel.Lifestyle.PerWebRequestLifestyleModule, Castle.Windsor"/>**

Here's the env. versions:

MVC 5 in .net framework 4.6
Castle.Core 3.3.0
IE 10 (miss the **castle.per-web-request-lifestyle-cache**)
IE 11 (miss the **castle.per-web-request-lifestyle-cache** )
Firefox ESR in debian 45.30  (runs well)
The controller instance is in the Castle Container. and the lifestyle is PerWebRequest.

Hope your help,
Thanks.

**Comment by jonorossi** [comment]
Hi, this is the Castle Windsor issue tracker, for help with your project please use [StackOverflow](http://stackoverflow.com/) (tagged with `castle-windsor`) or our users mailing list as per http://www.castleproject.org/get-involved/mailing-lists/.
