### ISSUE TITLE
Windsor - still supported?

### ISSUE THREAD

**Issue by rangercej** [castleproject/Windsor#158]
I'm looking for a replacement IoC/DI library, following the demise of both spring.net and unity. The last release of Windsor was over two years ago, and although I can see commits in Github over this time, there haven't been any further releases. Is there a plan for a 3.3.1 or 3.4 roll-up? Are any of the commits critical?

**Comment by jonorossi** [comment]
@rangercej I've actually got a 3.3.1/3.4 rollup release on my TODO list when I push out Castle Core 4.0, however there hasn't been many (if any) defect fixes mostly just documentation fixes.

Windsor is still used by many and is very mature with over a decade of use, however there isn't an active team anymore (most of us either don't use a container anymore or have moved to another platform) as you'll see with the piling up issues (many of which are support questions). Windsor isn't abandoned, those that have given so much time in the past just don't have the time at the moment, however we welcome people to get involved which is a great way to learn the library.

**Comment by jonorossi** [comment]
I should also respond to your question "still supported?", what does that really mean, I am not aware of any .NET container with commercial support other than the Microsoft one which as you'd mentioned is now dead. Stackoverflow is really "support" for most open source, and there are many users contributing there: http://stackoverflow.com/questions/tagged/castle-windsor

Windsor is and always will be open source, so always within your control.

**Comment by rangercej** [comment]
Bad terminology on my part - maintained would have been a better one to use. Ta for the info :-)
