### ISSUE TITLE
Overridable components

### ISSUE THREAD

**Issue by rohanaceres** [castleproject/Windsor#159]
Hi,

How can I override a component? I tried this article (http://milestone.topics.it/2012/03/castle-windsor-component-override_26.html), but I could not find neither `Overridable()` nor `IsOverridable` methods.

**Comment by jonorossi** [comment]
@rohanaceres that is a 5 year old article written for an older version of Windsor, however those two extension methods you are referring to are at the bottom of the article.

I have no idea what you are trying to do, but I recommend our docs: https://github.com/castleproject/Windsor/blob/master/docs/README.md

**Comment by rohanaceres** [comment]
@jonorossi I need to override the registered component for a specific interface. When I try to do so, an exception is thrown. I did not find a lifecycle or lifestyle that accomplished that.

**Comment by jonorossi** [comment]
@rohanaceres it is best to ask "how do I" questions on stackoverflow as there are many users monitoring the tags: http://www.castleproject.org/get-involved/mailing-lists/
