### ISSUE TITLE
Windsor 3.x is not compatible with Castle Core 4.x

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Windsor#161]
The dependency specification ([NuGet version range docs](https://docs.microsoft.com/en-us/nuget/create-packages/dependency-versions)) in the NuGet packages indicate any version of Castle Core from 3.3.0 is compatible, however 4.x versions are not.

    <dependencies>
      <dependency id="Castle.Core" version="3.3.0" />
    </dependencies>

This was also raised under Castle Core: https://github.com/castleproject/Core/issues/224.

**Comment by jonorossi** [comment]
Going to change the dependency specification to the following, we can then release a new Windsor version supporting Castle Core 4.x only.

    <dependencies>
      <dependency id="Castle.Core" version="[3.3.0,4.0)" />
    </dependencies>

**Comment by sloncho** [comment]
So, is there a ticket for making it compatible with Core 4.0? Is there a timeline?

**Comment by gregsdennis** [comment]
@sloncho I just made one.
