### ISSUE TITLE
Need some example of xml based registration of dependencies 

### ISSUE THREAD

**Issue by rahulsahay19** [castleproject/Windsor#164]
Hi Team,

Do you have any repo where in I can find few examples around XML based configuration for dependencies for API and WCF services both?

Thanks,
Rahul

**Comment by jonorossi** [comment]
Is the info in the docs or the sample project useful:
- https://github.com/castleproject/Windsor/blob/master/docs/wcf-facility-registration.md
- https://github.com/castleproject/Windsor/blob/master/src/Castle.Facilities.WcfIntegration.Demo/Global.asax.cs

I've not used the WCF facility myself, however generally code registration is our recommended practice for Windsor.

This is also the Castle Windsor issue tracker, for help with your project please use StackOverflow (tagged with `castle-windsor`) or our users mailing list as per http://www.castleproject.org/get-involved/mailing-lists/ for future questions.

**Comment by rahulsahay19** [comment]
I have gone through the docs. However, for WCF, it seems as if documentation and samples are obsolete. It needs to be updated with fairly working example with and without config stuff.

**Comment by jonorossi** [comment]
Unfortunately the nature of WCF is that there are limited people using it today. Once you get things sorted and I can see a bunch of StackOverflow questions with answers that might help feel free to send a pull request to update them.
