### ISSUE TITLE
Prevent unit tests that require administrator privileges from running by default

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Windsor#174]
Following on from the discussion in #165, we decided that it would be worthwhile to investigate improving the developer experience to not require those developing Windsor to have to set up a bunch of environment stuff (e.g. MSDTC and WCF bindings) and run Visual Studio as an administator.

We should be able to take advantage of NUnit's categories to enable these "integration tests" in addition to the use of the `[Explicit]` attribute, we should probably create an `[IntegrationTest]` attribute (or something similar) in our test project so we don't have to duplicate string. The NUnit documentation indicates that enabling a category will run any test marked as explicit. This will allow the build server to run the full set of tests while those not working on the WCF or automatic transaction facilities don't have to fuss about with annoying environment set up.

/cc @fir3pho3nixx

**Comment by fir3pho3nixx** [comment]
I manage to get a unit test only run with the following PR #175. 

To test it try `build NET40 RunUnitTests`.

Running just `build` still defaults to `build NET40 RunAllTests`.

`build NET40 RunUnitTests` passes in a cmd.exe window without `admin` privs.

**Comment by jonorossi** [comment]
Thanks, closing.
