### ISSUE TITLE
windsor controlfactory change the Url path in QA

### ISSUE THREAD

**Issue by dandamudi** [castleproject/Windsor#179]
my MVC app usining Windsor Controlfactory, everything looks OK in Local but in QA, when load the controller my Return URl path changes, Account/login adds automatically, even my app doesn't have Account controller and login view

Url should come like this : myappQA.com/Home/Index
but it comes like : myappQa.com/Account/login?/Home/index 

please help me

**Comment by jonorossi** [comment]
Hi, this is the Castle Windsor issue tracker, for help with your project please use [StackOverflow](http://stackoverflow.com/) (tagged with `castle-windsor`) or our users mailing list as per http://www.castleproject.org/get-involved/mailing-lists/.
