### ISSUE TITLE
Drop support for .NET 3.5/4.0 and Silverlight

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Windsor#185]
We've already made the decision to drop all Silverlight support in Windsor v4 following dropping support for Silverlight in Castle Core v4.

I (and others) think it is time we drop support for .NET Framework 3.5 and 4.0 for the next major Windsor version (v4), it is time because they are so old and mostly because it has now become effort to maintain and a lot of work for add .NET Core support while still keeping them working. Most .NET containers have removed support a while ago and today support:

- Autofac - .NET 4.5
- Ninject - .NET 4.5
- Simple Injector - .NET 4.0 and 4.5
- StructureMap - .NET 4.5
- Unity - .NET 4.5

Feel free to jump in either way, however be prepared to put forward a good argument if you believe we shouldn't remove support for .NET 3.5/4.0, Windsor 3.x will always be there for you if you really aren't already on .NET 4.5/4.6.

**Comment by jonnii** [comment]
Drop support, it's the right thing to do.

**Comment by fir3pho3nixx** [comment]
Silverlight down (#173, #180 and #184), .NET 3.5 next?

How should we approach this? CMD/MSBuild 1 PR, CSPROJ 1 PR then an experimental PR perhaps starting with one of the test fixtures so we can establish conventions for how we thing like:

!(DOTNET35 || SILVERLIGHT)
!DOTNET35
DOTNET35 || SILVERLIGHT
!DOTNET35 && !CLIENTPROFILE
!(SILVERLIGHT || CLIENTPROFILE || DOTNET35)

**Comment by fir3pho3nixx** [comment]
We have killed off support in the build process for the following: 

 - NET35
 - NET40
 - SILVERLIGHT
 - MONO

Now for the arduous task of build flag redux.

**Comment by fir3pho3nixx** [comment]
Let's start with NET35 @ #195. Will wait till you merge so I can continue without conflicts ...

**Comment by fir3pho3nixx** [comment]
Given #197, #198, #199

Think we have the last remnants of this done. 

We are keeping SL build flags so we can leap to Core on #145. 

We OK to close this issue @jonorossi ?

:) :) :)

**Comment by jonorossi** [comment]
> We OK to close this issue @jonorossi ?

Let's wait until those are merged, I'd like to do a quick check to see if there is anything left after that.

**Comment by fir3pho3nixx** [comment]
@jonorossi - what still needs to be done here? Can you think of anything I missed?

**Comment by jonorossi** [comment]
> what still needs to be done here? Can you think of anything I missed?

`buildscripts/*.nuspec` still have old entries. Have you done a final search through all files for "35", "3.5", ...?

**Comment by fir3pho3nixx** [comment]
Interesting... thought I got those. Will give it another look.

**Comment by fir3pho3nixx** [comment]
You right @jonorossi! There was some guff there ... #206. Will keep hunting and submit more PR's for what I find.

**Comment by fir3pho3nixx** [comment]
#207

**Comment by fir3pho3nixx** [comment]
GrepWin for 35 = nil

**Comment by fir3pho3nixx** [comment]
GrepWin for `4.0` = *Question*

Here we have an interesting conundrum to do with the tooling for MsBuild. 

In `buildscripts\build.cmd` we are currently using the following path: %windir%\microsoft.net\framework\v4.0.30319\msbuild.exe

This needs to change but we might need to update the build server before I can submit a PR. What do you think?

**Comment by fir3pho3nixx** [comment]
GrepWin for `40` = nil

**Comment by jonorossi** [comment]
> In buildscripts\build.cmd we are currently using the following path: %windir%\microsoft.net\framework\v4.0.30319\msbuild.exe
> 
> This needs to change but we might need to update the build server before I can submit a PR.

.NET 4.5 and 4.6 were all in-place upgrades of .NET 4.0 (we just compile against different reference assemblies), so the framework directory is the same.

**Comment by jonorossi** [comment]
Looks like we are done here. Many thanks @fir3pho3nixx for getting that all sorted.

**Comment by fir3pho3nixx** [comment]
@jonorossi - No worries 👍
