### ISSUE TITLE
Missing image (never imported from wiki) in MVC tutorial

### ISSUE THREAD

**Issue by MikeBeaton** [castleproject/Windsor#192]
`images/mvc-tutorial-resharper-unused-installer.png` referred to at line 29 of https://github.com/castleproject/Windsor/blob/master/docs/mvc-tutorial-part-4-putting-it-all-together.md does not exist in the docs directory.

It looks as if it was never imported when the docs were imported from the Wiki: https://github.com/castleproject/Windsor/commits/master/docs/images

I tried to find the original image from the Wiki, by using the internet archive, etc., (in order to make a quick pull request to fix this) but could not get to it.

**Comment by jonorossi** [comment]
Thanks @MikeBeaton, that file was missed from the import because of a bad `.gitignore` rule, see #193 where I've added it.
