### ISSUE TITLE
Resolve unmerged PRs and old issues

### ISSUE THREAD

**Issue by fir3pho3nixx** [castleproject/Windsor#196]
Can we please clean up the issues and PR's on this repo? Some of this stuff dates back to whoop whoop with some really old PR's.

**Comment by jonorossi** [comment]
@fir3pho3nixx oh definitely, however I think we need to work through them one by one as there is still valuable info in them. I'll try to find some time next week to knock a few down. It is really up to you what you think it more important, that mess of a backlog or .NET Core support, I'd personally put .NET Core support as :1st_place_medal:, but hopefully by the time we ship v4 we've cleared the backlog.

**Comment by fir3pho3nixx** [comment]
Awesome, I will keep chasing core. :)

**Comment by fir3pho3nixx** [comment]
@jonorossi - The PR's are looking cleaner. Good stuff!
