### ISSUE TITLE
Move ActiveRecord, NHibernate and Remoting facility to the attic

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Windsor#205]
The code for these facilities still remains in the Windsor repository, however they haven't been built or released since before Windsor 3.0. We've never released them to nuget.org, the packages on nuget.org are published by third parties.

If no one steps in to get them upgraded we'll move the code to the attic in case people want to easily access the source code in the future.

**Comment by fir3pho3nixx** [comment]
Just a thought, remoting is perhaps one I would delete unless of course we are keeping it for posterity...

**Comment by fir3pho3nixx** [comment]
There ya go :)

**Comment by fir3pho3nixx** [comment]
Can we re-open #203 and merge?

**Comment by fir3pho3nixx** [comment]
@jonorossi - Not be pushy but this stuff is getting in my way. Can we expedite pls?

**Comment by jonorossi** [comment]
I've moved the 3 facilities to a new repo in our deprecated GitHub org:
https://github.com/castleproject-deprecated/Castle.Windsor.Facilities
