### ISSUE TITLE
DI caching

### ISSUE THREAD

**Issue by chetankhargone** [castleproject/Windsor#208]
I am using `windsor castle` DI along the `Generic Repository pattern` for my `WebAPI` project.

 1. User forgets the password, so he calls ForgotPassword API. This API triggers an email with some random password.
 2. User login with username & random password via Login API.
 3. Post to login User wishes to reset the password via calling Reset Password API.
 4. User tries to login again with this new password.

But when he do so he gets the `User Credentials invalid` exception.While if he uses the old password he is able to login.

When I check in the database, password is updated correctly. But when I check DAL method that is making use of EF. The password is stil the OLD password.

But if I restart the website is IIS, then User can login with new password.

My DAL Method.

        public bool IsUserValid(string username, string password)
		{
            //#inspection line for me
			var user = GetUser(username);
			return user != null && password.EncryptStringAES() == user.Password;
		}
        
       private User GetUser(string username)
       {
          userName = !string.IsNullOrEmpty(userName) ? userName.Trim().ToLower() : string.Empty;
			return _userRepository.GetQuery()
				.FirstOrDefault(x => x.Email == userName);

       }
 

If I debug at #*inspection line for me*, I see that the user object has still old password.

DI Configuration.

    public void Install(IWindsorContainer container, IConfigurationStore store)
		{
			container.Register(
				Classes
				.FromAssemblyNamed("CustomerApp.EF")
				.WithService.Self()
				.LifestylePerWebRequest());
		}

I tried with `LifestylePerThread`& others but still same issue. While if I update my DAL as below.

    public bool IsUservalid(string username, string password)
		{
			using(AppContext entities = new AppContext()
            {
                var user = (from c in entities.tblUsers
                            where c.Email == username
                            select c);
                //if I debug now, no issue 
            }
		}

Above patch is not Valid for me. 

So what is causing this & how do I address this issue?

Any help/suggestion highly appreciated.
Thanks.

**Comment by devworker55** [comment]
Hi @chetankhargone, could you give us a little more information? e.g are your repositories in "CustomerApp.EF" as well, meaning are they registered PerWebRequest also? How is the  DbContext been injected assigned in the repository class?

**Comment by chetankhargone** [comment]
Hi @devworker55 , thanks for the follow-up. Please find the below answers to your questions.

1. Yes, all my repositories are in CustomerApp.EF & they are registered as `.LifestylePerWebRequest());` mode.
2. I didn't get your question.
3. No.
4. Yes. The issue is reproducible irrespective of the number of  users.

Hope above inputs suffice you. In case any further details required,please let me know.

Thanking You.

**Comment by jonnii** [comment]
@chetankhargone you're probably better off asking this on stackoverflow.

**Comment by devworker55** [comment]
@chetankhargone I found your question on SO so I will continue with my responses there...

**Comment by jonorossi** [comment]
> you're probably better off asking this on stackoverflow.

Thanks @jonii, yep StackOverflow is the place for help with your project, here is my usual saved reply:

Hi, this is the Castle Windsor issue tracker, for help with your project please use [StackOverflow](http://stackoverflow.com/) (tagged with `castle-windsor`) or our users mailing list as per http://www.castleproject.org/get-involved/mailing-lists/.
