### ISSUE TITLE
Resolve after ConfigureAwait(false) in ASP.NET application

### ISSUE THREAD

**Issue by lukas-lansky** [castleproject/Windsor#209]
We are slowly moving a large codebase towards dependency injection. We decided that to be able to start creating services that can be used across the codebase, we will allow ourselves to do service-locatorish approach towards resolution in static contexts: we ask static composition root to ``Resolve<T>()`` our service. This is of course not optimal, but is allow us to move gradually. When static contexts fade away, we will forbid ourselves to do this.

Now, we are also started to introduce async-await and we are consistently applying ``ConfigureAwait(false)`` to be able to utilize the thread pool better. We know that we are going to loose better parts of ``HttpContext.Current`` and we don't care too much as we don't want to depend on it anyway. But Windsor's ``PerWebRequestLifestyleModule`` depends on it, so we are unable to resolve components after the first await transition.

When looking into Windsor source code, I see that you use ``CallContext`` for saving state at ``CallContextScope`` and I wonder whether you thought about saving ``PerWebRequest`` state into it instead of ``HttpContext.Current.Items``. Isn't this something that ASP.NET Core support is going to demand anyway as the role of ``HttpContext`` is diminshed there? (Not sure at all, honest question.)

**Comment by jonorossi** [comment]
I don't remember exactly, but I think when @kkozmic did the refactor for scoped lifestyles for Windsor 3.0 the use of `CallContext` was added, the `PerWebRequest` lifestyle implementation definitely predates that and has always depended on `System.Web`. There is a bit more info in the docs: https://github.com/castleproject/Windsor/blob/master/docs/lifestyles.md.

With the history aside, yes the implementation would have to change for the `PerWebRequest` lifestyle to be used with ASP.NET Core, however changing it would likely be more work and than just using a simple scoped lifestyle, others have already made some progress with a discussion in #120.

**Comment by jonorossi** [comment]
Obviously a lot has happened in the last few years with ASP.NET Core and Windsor's per web request lifestyle. Closing this as stale, feel free to reopen if there is new info.
