### ISSUE TITLE
Migrating to the VS2017 project structure is ***Tough Bananas***

### ISSUE THREAD

**Issue by fir3pho3nixx** [castleproject/Windsor#214]
This is akin to plucking your pubes one at a time with a tweezer over a random Thread.Sleep(2000) interval using 2/3 processor cores(3 if you are me). 

The MsBuild infrastructure needs a complete rethink(do over). 

1. Xml namespaces are not a thing anymore in CsProj files

```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
```

Becomes

```xml
<Project  Sdk="Microsoft.NET.Sdk">
```

2. TargetFramework becomes TargetFrameworks to support dotnet standard/core. 

```xml
<PropertyGroup>
    <TargetFrameworks>net45;netstandard1.6</TargetFrameworks>
</PropertyGroup>
```

This changes how build targeting works.

3. Build targeting needs to be change for every CsProj. 

So stuff like

```xml
<PropertyGroup>
  <ProjectType>Local</ProjectType>
  <ProductVersion>9.0.30729</ProductVersion>
  <SchemaVersion>2.0</SchemaVersion>
  <ProjectGuid>{60EFCB9B-E3FF-46A5-A2D2-D9F0EF75D5FE}</ProjectGuid>
  <Configuration Condition=" '$(Configuration)' == '' ">NET45-Debug</Configuration>
  <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
  <ProjectGuid>{60EFCB9B-E3FF-46A5-A2D2-D9F0EF75D5FE}</ProjectGuid>
  <AssemblyName>Castle.Windsor</AssemblyName>
  <OutputType>Library</OutputType>
  <AppDesignerFolder>Properties</AppDesignerFolder>
  <RootNamespace>Castle</RootNamespace>
  <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
  <SignAssembly>true</SignAssembly>
  <AssemblyOriginatorKeyFile>..\..\buildscripts\CastleKey.snk</AssemblyOriginatorKeyFile>
  <FileUpgradeFlags>
  </FileUpgradeFlags>
</PropertyGroup>
```

Needs to magically become

```xml
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='NET45-Debug|net45|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\NET45-Debug\</OutputPath>
    <DefineConstants>TRACE;DEBUG;DOTNET;DOTNET45</DefineConstants>
    <DocumentationFile>bin\NET45-Debug\Castle.Windsor.XML</DocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>1591</NoWarn>
    <DebugType>full</DebugType>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <ErrorReport>prompt</ErrorReport>
    <Prefer32Bit>false</Prefer32Bit>
</PropertyGroup>
```

4. MsBuildExtensions then bites you on the ass, because we now have 2 flavours. The one Castle.Windsor has and the one defined in `Sdk.props`. Pathing between the two is PITA. 

5. Compile include is not a thing anymore. 

```xml
<Compile Include="<folder>\<file>.cs" />
```

6. Sdk.props cannot find Microsoft.Common.props. This is perhaps the most frustrating thing. It is kicked out of `Build.proj` whilst running build.cmd from the root folder in admin mode. Faaark!

7. Nursing dead code in #205 does not make this any easier because grepping across *.csproj makes things harder, there is just too much noise that comes up. 

I recommend keeping the bootstrapper build.cmd in the root folder, and then introducing something like FAKE for doing this, with a completely new .csproj structure supporting dotnet45 at first and then standard 1.6 later(obviously including first class NuGet support). This is one fakking huge PR. Also think moving to appveyor would be better than managing VM's running teamcity. Targetting new frameworks adds extra weight to the build/publish solution. If you want to look at examples please see how I have done it here: https://github.com/cryosharp/fluentwindsor. 

Think it is time you guys start thinking about making me a member. I can get us to dotnet core faster and make things a lot lighter in terms of maintenance.

**Comment by fir3pho3nixx** [comment]
Gentleman, this gets more mental the deeper I go. I am not going to go away until this is done(as I said you will hate me ... #165). 

@jonorossi - I just want to thank you for you involvement so far. Please don't be disparaged. I believe we can get this done. Please bear with me.

Doing incremental PR's is not an option. I personally think the flux at Microsoft has created a divergence in terms of how the MsBuild works and backwards compatibility has been forgone. This makes the previous weeks of my clean up m00t in terms of build stuff. Disappointing for me especially but I willing to take the hit. This has left me frustrated though.  

The new learnings/frustrations I found tonight: 

1. Baking binary dependencies into master has not done us any favours. NUnit being a case in point. Charlie Pool deprecated the ExpectedException attribute a while ago. Not using a package management for NUnit has hidden this breaking change. Removing this from the code was a pain in the arse but I have done it. 

2. Breaking changes around logging abstractions from Core has caused issues in getting tests to compile for Windsor. I honestly don't believe logging should be abstracted for each logging dependency. That is why you use NuGet. It should be reduced to a lambda func based subscription from a static member which calls out to something that the client code of windsor does, not Windsor or Core itself. This will make logging cloud friendly. Did you know azure application insights was a thing? Log shipping becomes weird in this space. We should stop doing that.

3. The size of this PR is going to be butt fucking huge. No matter which way you cut it. I think we should just do it. I am not keen on trying to find incremental ways anymore. I am also not keen on waiting for PR's to take 2/3 days to merge. There is clearly demand for a core version of this(myself included). I will honour the WcfIntegration responses(as in #165). I cant tolerate the maintenance of dead code for #203, https://github.com/castleproject/Attic/pull/2, #205. Please can we merge my PR's? I am running out of patience on this.   

4. On the positive side, the polyfills from Core helped heaps to get things to compile. This is a good thing. 

Please see the size of the change for the DNM-PR(DO NOT MERGE PR) just to get an idea. You are welcome to tell me off but I am the only guy doing stuff here ...

**Comment by jonorossi** [comment]
@fir3pho3nixx as per our [code of conduct](https://www.apache.org/foundation/policies/conduct) please "be careful in the words that we choose", excessive or unnecessary profanity is unwelcome and unprofessional. To be clear, the first paragraph of your issue description is what pushed me over the line to call you out on this but the constant profanity is unnecessary, I would appreciate if you could adhere to our code of conduct.

> The MsBuild infrastructure needs a complete rethink(do over).

As I've mentioned several times in other issues we should ignore the existing MSBuild based build scripts and dump all that mess that hooks into the csproj project files when using the new .NET tooling as it supports multiple platforms itself.

> Think it is time you guys start thinking about making me a member.

Not to sound rude but that isn't the way it works here, we have since 2003 followed the [Apache Software Foundation process](https://community.apache.org/contributors/#moving-from-contributor-to-committer) (Windsor started life in the Apache Avalon project). Under this process a candidate is nominated (http://www.castleproject.org/about/team/), the Project Management Committee votes, and the committer is invited. I'm not saying this process is needed anymore (the PMC would have to vote to remove it) but more than anything trust has to be built, for example I don't even know your name other than "Gav".

> I personally think the flux at Microsoft has created a divergence in terms of how the MsBuild works and backwards compatibility has been forgone. This makes the previous weeks of my clean up m00t in terms of build stuff. Disappointing for me especially but I willing to take the hit. This has left me frustrated though.

I'm confused a little by your comments here, as I mentioned I had made it clear that I didn't see a future for those build scripts, most of your commits though were actually affecting the source code, the changes to those build scripts wasn't wasted, it allows us to easily see what features are left in them that are currently left to port to the new tools.

> Baking binary dependencies into master has not done us any favours. NUnit being a case in point. Charlie Pool deprecated the ExpectedException attribute a while ago. Not using a package management for NUnit has hidden this breaking change. Removing this from the code was a pain in the arse but I have done it.

NuGet or no-NuGet wouldn't have made a difference here, we have just been using an old version of NUnit. Windsor committing binaries predates NuGet by many many years. I agree that we should be upgrading NUnit just as I did with the recent clean up in Castle Core.

> Breaking changes around logging abstractions from Core has caused issues in getting tests to compile for Windsor. I honestly don't believe logging should be abstracted for each logging dependency. That is why you use NuGet. It should be reduced to a lambda func based subscription from a static member which calls out to something that the client code of windsor does, not Windsor or Core itself. This will make logging cloud friendly. Did you know azure application insights was a thing? Log shipping becomes weird in this space. We should stop doing that.

What breaking changes occurred with the logging abstractions in Castle Core 4.0? I don't recall we made any, we didn't note any in the release notes. This is a discussion for another issue, but again the logging integration used to be used by the many Castle projects and it predates the whole Azure platform.

> The size of this PR is going to be **** ****ing huge(#215). No matter which way you cut it. I think we should just do it. I am not keen on trying to find incremental ways anymore. I am also not keen on waiting for PR's to take 2/3 days to merge. There is clearly demand for a core version of this(myself included). I will honour the WcfIntegration responses(as in #165). I cant tolerate the maintenance of dead code for #203, castleproject/Attic#2, #205. Please can we merge my PR's? I am running out of patience on this.

I'm not even sure how to respond to this, so I just won't as your aggression is really showing through. I don't and never have been paid to work on Castle, 2/3 days to merge a PR shouldn't be seen as unacceptable.

**Comment by fir3pho3nixx** [comment]
Ok @jonorossi 

> @fir3pho3nixx as per our code of conduct please "be careful in the words that we choose", excessive or unnecessary profanity is unwelcome and unprofessional. To be clear, the first paragraph of your issue description is what pushed me over the line to call you out on this but the constant profanity is unnecessary, I would appreciate if you could adhere to our code of conduct.

I have updated comments to remove bad words. I wont do that again. Let's remember I was trying to help. Start there and you will see the light. 

> Gav: The MsBuild infrastructure needs a complete rethink(do over).

>> Jonothan: As I've mentioned several times in other issues we should ignore the existing MSBuild based build scripts and dump all that mess that hooks into the csproj project files when using the new .NET tooling as it supports multiple platforms itself.

Where is your plan fella? You cannot expect willing contributor's to understand that. You need a plan where is it?

> Gav: Think it is time you guys start thinking about making me a member.

>> Jonothan: Not to sound rude but that isn't the way it works here, we have since 2003 followed the Apache Software Foundation process (Windsor started life in the Apache Avalon project). Under this process a candidate is nominated (http://www.castleproject.org/about/team/), the Project Management Committee votes, and the committer is invited. I'm not saying this process is needed anymore (the PMC would have to vote to remove it) but more than anything trust has to be built, for example I don't even know your name other than "Gav".

Not to sound rude but think it is time we have a call? Seriously committee? Your project is dying. Is this how you roll in Oz? Common man! My email is listed on Github. Stop messing about. Your God complex needs to ratchet itself down a notch. You also have members willing to PAY for contributions. This was my attempt at getting admin access to your build server. Your doing my head in. 

> Gav: I personally think the flux at Microsoft has created a divergence in terms of how the MsBuild works and backwards compatibility has been forgone. This makes the previous weeks of my clean up m00t in terms of build stuff. Disappointing for me especially but I willing to take the hit. This has left me frustrated though.

>> Jonothan: I'm confused a little by your comments here, as I mentioned I had made it clear that I didn't see a future for those build scripts, most of your commits though were actually affecting the source code, the changes to those build scripts wasn't wasted, it allows us to easily see what features are left in them that are currently left to port to the new tools.

Understandable for most who speak english. Confusion for me is how we just let this go and move on to the next thing. In fact the whole community is confused. There is no migration, just let it go. There is no reference. Move on!

>Gav: Baking binary dependencies into master has not done us any favours. NUnit being a case in point. Charlie Pool deprecated the ExpectedException attribute a while ago. Not using a package management for NUnit has hidden this breaking change. Removing this from the code was a pain in the arse but I have done it.

>> Jonothan: NuGet or no-NuGet wouldn't have made a difference here, we have just been using an old version of NUnit. Windsor committing binaries predates NuGet by many many years. I agree that we should be upgrading NUnit just as I did with the recent clean up in Castle Core.

Yes it would. Auto upgrades in your build process would have prevented you from releasing a new version. This means it would have been dealt with sooner. Common man, committing binaries is bad. Just admit it!

> Gav: Breaking changes around logging abstractions from Core has caused issues in getting tests to compile for Windsor. I honestly don't believe logging should be abstracted for each logging dependency. That is why you use NuGet. It should be reduced to a lambda func based subscription from a static member which calls out to something that the client code of windsor does, not Windsor or Core itself. This will make logging cloud friendly. Did you know azure application insights was a thing? Log shipping becomes weird in this space. We should stop doing that.

>> Jonothan: What breaking changes occurred with the logging abstractions in Castle Core 4.0? I don't recall we made any, we didn't note any in the release notes. This is a discussion for another issue, but again the logging integration used to be used by the many Castle projects and it predates the whole Azure platform.

Whoa Nelly! Tried to see what happens when you upgrade to VS2017. I leave that one to you. 

>Gav: The size of this PR is going to be **** ****ing(<- sorry for this) huge(#215). No matter which way you cut it. I think we should just do it. I am not keen on trying to find incremental ways anymore. I am also not keen on waiting for PR's to take 2/3 days to merge. There is clearly demand for a core version of this(myself included). I will honour the WcfIntegration responses(as in #165). I cant tolerate the maintenance of dead code for #203, castleproject/Attic#2, #205. Please can we merge my PR's? I am running out of patience on this.

>> Jonothan: I'm not even sure how to respond to this, so I just won't as your aggression is really showing through. I don't and never have been paid to work on Castle, 2/3 days to merge a PR shouldn't be seen as unacceptable.

I am not being paid to work on this mate. Ask @hikalkan I never took his offer. This is pure passion fella.

**Comment by fir3pho3nixx** [comment]
![ba-fool](https://cloud.githubusercontent.com/assets/607402/24127286/5133f334-0dcb-11e7-9ebf-9e47e4435a3c.jpg)

**Comment by ganjeii** [comment]
@jonorossi seriously dude... grow a pair.


> @fir3pho3nixx as per our [code of conduct](https://www.apache.org/foundation/policies/conduct) please "be careful in the words that we choose", excessive or unnecessary profanity is unwelcome and unprofessional. To be clear, the first paragraph of your issue description is what pushed me over the line to call you out on this but the constant profanity is unnecessary, I would appreciate if you could adhere to our code of conduct.
> 
> > The MsBuild infrastructure needs a complete rethink(do over).
> 
> As I've mentioned several times in other issues we should ignore the existing MSBuild based build scripts and dump all that mess that hooks into the csproj project files when using the new .NET tooling as it supports multiple platforms itself.
> 
> > Think it is time you guys start thinking about making me a member.
> 
> Not to sound rude but that isn't the way it works here, we have since 2003 followed the [Apache Software Foundation process](https://community.apache.org/contributors/#moving-from-contributor-to-committer) (Windsor started life in the Apache Avalon project). Under this process a candidate is nominated (http://www.castleproject.org/about/team/), the Project Management Committee votes, and the committer is invited. I'm not saying this process is needed anymore (the PMC would have to vote to remove it) but more than anything trust has to be built, for example I don't even know your name other than "Gav".
> 
> > I personally think the flux at Microsoft has created a divergence in terms of how the MsBuild works and backwards compatibility has been forgone. This makes the previous weeks of my clean up m00t in terms of build stuff. Disappointing for me especially but I willing to take the hit. This has left me frustrated though.
> 
> I'm confused a little by your comments here, as I mentioned I had made it clear that I didn't see a future for those build scripts, most of your commits though were actually affecting the source code, the changes to those build scripts wasn't wasted, it allows us to easily see what features are left in them that are currently left to port to the new tools.
> 
> > Baking binary dependencies into master has not done us any favours. NUnit being a case in point. Charlie Pool deprecated the ExpectedException attribute a while ago. Not using a package management for NUnit has hidden this breaking change. Removing this from the code was a pain in the arse but I have done it.
> 
> NuGet or no-NuGet wouldn't have made a difference here, we have just been using an old version of NUnit. Windsor committing binaries predates NuGet by many many years. I agree that we should be upgrading NUnit just as I did with the recent clean up in Castle Core.
> 
> > Breaking changes around logging abstractions from Core has caused issues in getting tests to compile for Windsor. I honestly don't believe logging should be abstracted for each logging dependency. That is why you use NuGet. It should be reduced to a lambda func based subscription from a static member which calls out to something that the client code of windsor does, not Windsor or Core itself. This will make logging cloud friendly. Did you know azure application insights was a thing? Log shipping becomes weird in this space. We should stop doing that.
> 
> What breaking changes occurred with the logging abstractions in Castle Core 4.0? I don't recall we made any, we didn't note any in the release notes. This is a discussion for another issue, but again the logging integration used to be used by the many Castle projects and it predates the whole Azure platform.
> 
> > The size of this PR is going to be **** ****ing huge(#215). No matter which way you cut it. I think we should just do it. I am not keen on trying to find incremental ways anymore. I am also not keen on waiting for PR's to take 2/3 days to merge. There is clearly demand for a core version of this(myself included). I will honour the WcfIntegration responses(as in #165). I cant tolerate the maintenance of dead code for #203, [castleproject-deprecated/Attic#2](https://github.com/castleproject-deprecated/Attic/pull/2), #205. Please can we merge my PR's? I am running out of patience on this.
> 
> I'm not even sure how to respond to this, so I just won't as your aggression is really showing through. I don't and never have been paid to work on Castle, 2/3 days to merge a PR shouldn't be seen as unacceptable.
