### ISSUE TITLE
why I can not resolve my type?

### ISSUE THREAD

**Issue by stonezhu870** [castleproject/Windsor#217]
environment：
Castle.Core 3.3
Castle.Windsor 3.4

1、I register my ITest type.
     IocManager.IocContainer.Register(
             Component.For《ITest》()
                      .ImplementedBy《Test》()
                      .LifeStyle.Singleton
    );

2、I debugger comonentRegistration.cs  in Windsor project‘s 
![qq 20170323171350 1](https://cloud.githubusercontent.com/assets/3832691/24240731/9ac57774-0fed-11e7-8e94-acedaa3bb16f.png)

 please look at “typeof(TService).GetHashCode()” = 45562356

3、Go next, why the type‘s hashcode changed,
![default](https://cloud.githubusercontent.com/assets/3832691/24240564/0f0997b0-0fed-11e7-9a96-20cf4882c87d.png)

Such registration, cause I can not resolve my   types

thx, please help me，why the same type but the hashcode different in diff method

**Comment by stonezhu870** [comment]
please help me

**Comment by jonorossi** [comment]
@stonezhu870 there isn't enough info here to go on. Can you show the names of the two types rather than their hash codes.
