### ISSUE TITLE
Castle.Core 4.x compatibility

### ISSUE THREAD

**Issue by gregsdennis** [castleproject/Windsor#227]
In #161 a bandaid was applied to the Nuget package to prevent upgrades to Castle.Core 4.x.

Are we going to see a version that *is* compatible?

**Comment by jonorossi** [comment]
Yes, we are currently working to move our build processes to the new VS2017 tooling and move from TeamCity to AppVeyor. Once this work is done I'm planning to get a new release out that upgrades to Castle Core 4.0, is this currently blocking you?

**Comment by gregsdennis** [comment]
Not blocking per se, but Moq > v4.7.0 depends on Core v4.x, so I'm stuck with lower versions until this is released.

Do you have a timeline?

**Comment by jonorossi** [comment]
Ah, I thought Moq was still ILMerging Castle.Core.dll into Moq.dll, it looks like they are no longer doing that.

Timeline... should be in the next 2 weeks.

**Comment by jeremymeng** [comment]
> I thought Moq was still ILMerging Castle.Core.dll into Moq.dll,

ILMerge doesn't work on .NET Core so we moved to depend on NuGet packages for both .NET Framework and .NET Core.

**Comment by dove** [comment]
NSubstitute 2 would appear to be in same boat as Moq, it now has Castle.Core >= 4 as a dependency where is had none in 1.*

**Comment by alinapopa** [comment]
Opened PR #235

**Comment by gregsdennis** [comment]
@jonorossi so is this resolved?

**Comment by fir3pho3nixx** [comment]
@gregsdennis - Sorry I am jumping here, but yes it was resolved. We are preparing a release. Any day now :)
