### ISSUE TITLE
Add conditional compilation for features only in .NET framework, like Castle.Core

### ISSUE THREAD

**Issue by alinapopa** [castleproject/Windsor#238]
- [x] `FEATURE_APPDOMAIN`
    - [x] `FEATURE_SERIALIZATION`
    - [x] `FEATURE_SECURITY_PERMISSIONS` 
    - [x] `FEATURE_REMOTING`
    - [x] `FEATURE_SYSTEM_CONFIGURATION`
#145

**Comment by fir3pho3nixx** [comment]
Can we do this in a new branch and not `refactor-build`? Something like `netcore` perhaps?

**Comment by alinapopa** [comment]
Yes it would be good to do this in a new branch.

**Comment by fir3pho3nixx** [comment]
Ok, so I think you have write access. You are welcome to create a new branch. @jonorossi are you OK with this?

**Comment by jonorossi** [comment]
Definitely a new branch. Both of you have write access to push a new branch, yes happy with one named `netcore`. Were you intending to continue doing PRs into the branch like the refactor-build one for code reviews?

**Comment by fir3pho3nixx** [comment]
I would say PR's are always a must. It is important we check each other's work.

**Comment by fir3pho3nixx** [comment]
@alinapopa - Anything I can help with here?

**Comment by alinapopa** [comment]
@fir3pho3nixx The remaining thing here is to add FEATURE_APPDOMAIN

**Comment by alinapopa** [comment]
Completed
