### ISSUE TITLE
Set up build for .NET Core

### ISSUE THREAD

**Issue by alinapopa** [castleproject/Windsor#241]
Using AppVeyor and Travis CI, similar to Castle.Core - see Castle.Core issue [241](https://github.com/castleproject/Core/issues/241)

**Comment by fir3pho3nixx** [comment]
@alinapopa && @jonorossi - How do we want to do this? 

All the `refactor-build` code is merged into `netcore` branch.

Should I just enable tests for netcoreapp in AppVeyor and create a failed build using a PR(netcore-tests -> netcore)? 

Also do we want an issue for getting mono rocking? We had this before, I would like to bring it back. I just need guidance from you as to where and how we place this.

**Comment by alinapopa** [comment]
> Should I just enable tests for netcoreapp in AppVeyor 

Yes I think this is needed.

**Comment by jonorossi** [comment]
> All the refactor-build code is merged into netcore branch.

Is there much point in keeping the refactor-build branch, we are so close to getting a .NET Standard build going we aren't likely to release anything without that now?

> Should I just enable tests for netcoreapp in AppVeyor and create a failed build using a PR(netcore-tests -> netcore)?

I agree with @alinapopa, yes.
 
> Also do we want an issue for getting mono rocking? We had this before, I would like to bring it back on Travis. I just need guidance from you as to where and how we place this.

We didn't have this for Windsor before only Castle Core, however since you've been able to get it working pretty cleanly for Castle Core I don't see why not adding it and working through any issues while we sort out the remaining bits for .NET Standard.

**Comment by fir3pho3nixx** [comment]
Cool, will get this tests failing on a new branch called `netcore-tests` and raise a PR to `netcore` so we can start looking at the failures and raising more issues. I will also raise a separate issue for mono but leave it out of the `ready` column until we have made more progress with the tests. 

👍

**Comment by fir3pho3nixx** [comment]
We now have a good build in `netcore` and 3 failing tests along with 1 ignored test in `netcore-tests`. Looking good people! #277

**Comment by jonorossi** [comment]
@fir3pho3nixx what's the plan for restoring `WillRegisterServiceWithServiceCatalog` in `src/Castle.Facilities.WcfIntegration.Tests/Service/ServiceHostFixture.cs` which you marked ignored?

**Comment by fir3pho3nixx** [comment]
Sorry was looking into the dotnet test issue on Linux. The vstest team has scheduled a fix for 15.3 milestone. 

I think we should fix it. Will take another look when I am back from hols next week.

**Comment by fir3pho3nixx** [comment]
Got pwned by JetBrains, dotmemory was interfering with the endpoint discovery in this test. #285

**Comment by fir3pho3nixx** [comment]
@jonorossi - will wait for you to close this one. 👍
