### ISSUE TITLE
Use the latest NUnitTestAdapter for running tests (3.8.0-alpha1)

### ISSUE THREAD

**Issue by alinapopa** [castleproject/Windsor#243]
Ref: #234 

The latest adapter does not run on both windows and linux. We can only progress this once the issue below is dealt with. 

https://github.com/nunit/nunit3-vs-adapter/issues/324

**Comment by fir3pho3nixx** [comment]
Turns out this is a problem with nunit/xunit also. Created a repro @ https://github.com/fir3pho3nixx/nunit-adapter-vs-xunit which proves the case.

**Comment by fir3pho3nixx** [comment]
@all - I have just seen the commit go in that fixes this in the test adapter. As soon as they release I will raise a PR

**Comment by fir3pho3nixx** [comment]
[ping back from ms](https://github.com/Microsoft/vstest/issues/865#issuecomment-312255464)

**Comment by fir3pho3nixx** [comment]
Just an update, there appears to be more problems with the latest nightly build that is in preview. Things appear to be going backwards. I am still actively investigating this ... will keep this issue updated with any pertinent info.

**Comment by fir3pho3nixx** [comment]
This is definitely possible now with [netcoreapp2.0 now](https://github.com/castleproject/Windsor/pull/376/commits/bc2d2cb496a09a5c8c5f1a636bb44642a6a2c117).

**Comment by fir3pho3nixx** [comment]
Can I go ahead an upgrade?

**Comment by jonorossi** [comment]
> Can I go ahead an upgrade our test libraries + appveyor build?

Yep, go for it.

**Comment by fir3pho3nixx** [comment]
Closing in anticipation of: https://github.com/castleproject/Windsor/pull/381
