### ISSUE TITLE
Cannot resolve Lazy<IEmptySubService[]>

### ISSUE THREAD

**Issue by Fabske** [castleproject/Windsor#25]
When registering both the CollectionResolver and the Lazy resolver, trying to resolve Lazy<IEmptySubService[]> works, but when accessing the Lazy.Value it throws an exception

<b>Failed 1 tests.</b>
Castle.MicroKernel.ComponentNotFoundException : No component for supporting the service CastleArrayResolverLab.IEmptySubService[] was found

Test can be download using this url : https://skydrive.live.com/redir?resid=6C6DB85BD06DD466!172&authkey=!AExF8hHR7J3u6gc

**Comment by fir3pho3nixx** [comment]
The context of this issue is lost. The links are no longer relevant and we have no repro. Closing.
