### ISSUE TITLE
Remove DOTNET45 compilation symbol

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Windsor#291]
If we still need the conditional code then we should use a symbol that explains its use.

@alinapopa Logging this one for you since you brought it up, let me know if you can't get to it.

**Comment by fir3pho3nixx** [comment]
Okay, that is annoying. 

I was trigger happy on pushing to origin(which is my fork) and then using repeated `git reset head~ && git push --force` but then github thought it would be a good idea to `troll` this issue with non-existent commits in my fork????

**Comment by fir3pho3nixx** [comment]
Deep linking of issues a bit far perhaps?

**Comment by jonorossi** [comment]
Thanks guys, merged.
