### ISSUE TITLE
Reword changelog for v4.0

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Windsor#292]
@fir3pho3nixx I think we need to do a better job describing the changes so they make more sense from a user's point of view. Removing the old SL symbols can be merged into a single line (we can put multiple issues/PRs in parenthesis).

**Comment by fir3pho3nixx** [comment]
No probs. Will submit a PR. 👍

**Comment by fir3pho3nixx** [comment]
@jonorossi - PR over here: https://github.com/castleproject/Windsor/pull/294

**Comment by jonorossi** [comment]
I made a few extra changes to add .NET Standard/Core support, also to make it clearer we didn't remove Mono support, the symbols that were there really didn't help supporting Mono anyway.
