### ISSUE TITLE
WindsorContainer can generate the same name for 2 different instances in multi threading environments

### ISSUE THREAD

**Issue by npandrei** [castleproject/Windsor#301]
It looks like the name of a container is generated like this: 

`AppDomain.CurrentDomain.FriendlyName + " \xD83C\xDFF0 " + (object) ++WindsorContainer.instanceCount`

but if you have a multi threading env, then that ++WindsorContainer.instanceCount is not thread safe, and you end up generating the same name for 2 containers. This may not be a problem in general, but if you add them as ChildContainers, then one of them is ignored.

I assume this can be replaced to use Interlocked.Increment() or something similar.

PS: I am using the 3.4.0 version

Thanks

**Comment by jonorossi** [comment]
Fixed in #301, will be released tomorrow. Thanks.
