### ISSUE TITLE
readme.txt is out of date

### ISSUE THREAD

**Issue by fir3pho3nixx** [castleproject/Windsor#305]
[This](https://github.com/castleproject/Windsor/blob/master/buildscripts/readme.txt) get's displayed when NuGet's are installed and needs updating.

**Comment by jonorossi** [comment]
I think we can probably delete this file completely. I doubt many people find value in that file popping up in their editor when, surely people have found the project here and are installing the package, not the other way around. And if you did want some help you'd have closed the readme after install and can't get it back.

**Comment by fir3pho3nixx** [comment]
Cool, will blitz it when I get a gap.

**Comment by jonorossi** [comment]
Merged #332.
