### ISSUE TITLE
Migration .NET Project (Framework 6.2 ) to .NET Core

### ISSUE THREAD

**Issue by amruthbinish** [castleproject/Windsor#312]
I have the plan to migrate projects ((Framework 4.6.2 )  to .NET core. The existing project we are using Castle.Core, Version=4.0.0.0 . Can any one answer ,Is Castle.Core support ,NET Core  ?  if yes which Version of .NET Core (Core 1.0 , 1.1 and 2.0) it's support? Thanks

**Comment by jonorossi** [comment]
Firstly this is the Castle Windsor issue tracker not the Castle Core one, you'll see .NET Core is mentioned in the readme there: https://github.com/castleproject/Core.

- Castle Core supports .NET Standard 1.3+
- Castle Windsor supports .NET Standard 1.6+

**Comment by amruthbinish** [comment]
Thanks !!
