### ISSUE TITLE
Installers discovery limitation under ASP.NET Core 2.0 and Linux?

### ISSUE THREAD

**Issue by xlegalles** [castleproject/Windsor#314]
I'm still trying to investigate further but the fact is that our service runs perfectly with a Docker image microsoft/aspnetcore 2.0.0-preview2-nanoserver but it does not start with the 2.0.0-preview2-stretch version. We get an exception when trying to resolve an interface registered with AsFactory().
`Unhandled Exception: Castle.MicroKernel.ComponentNotFoundException: No component for supporting the service`

Do you know if there are actually some limitations?

Thank you

**Comment by jonorossi** [comment]
> Do you know if there are actually some limitations?

There are no known Windsor defects with any .NET Core 2.0 previews.

The first place to start is the actual exception. You've cut the exception message short:

```csharp
string.Format("No component for supporting the service {0} was found", service.FullName)
```

Make sure that you are indeed running the same code and that your registration code is being run with the newer ASP.NET Core preview.

**Comment by xlegalles** [comment]
This is for sure the same code: the only thing that changes is the original image in the DockerFile as I explained, nothing else. Another possibility is that we discover dynamically installers from current available assemblies and the factory registration may be missing.
I will investigate further tomorrow.

**Comment by xlegalles** [comment]
So, there is definitely a different behavior between both OS but it is not related to `AsFactory` but better to the discovery of installers. Here is the incriminated code:
```
string assemblyFilter = "kautomate.*.dll"
var mainDirectory = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
Container.Install(FromAssembly.InDirectory(new AssemblyFilter(mainDirectory, assemblyFilter)));
```
Under NanoServer the path is `c:\app` and the factory installer is well discovered/invoked.
Under Linux, the path is `/app` and the installer is not invoked.

The application is strictly the same.

Do you have an idea?

**Comment by xlegalles** [comment]
Forget it: files are case sensitive under Linux :(
