### ISSUE TITLE
ReflectionUtil.GetAssemblyNamed causes FileNotFoundException for existing assembly

### ISSUE THREAD

**Issue by rr-media** [castleproject/Windsor#315]
- .NET Core 2.0 preview 2
- Castle.Windsor 4.0.0.0

ReflectionUtil.GetAssemblyNamed fails with FileNotFound exception if you try to load assembly from outside bin directory.

I attached debugger and it shows that the first GetAssemblyName(filePath) call works successfully but the following LoadAssembly(assemblyName) causes this exception probably because AssemblyName.CodeBase property is null in .NET Core. This behavior affects installations based on FromAssembly.InDirectory directive that worked just fine in Full Framework.

There is a work-around - add custom assembly resolver that will explicitly load such assemblies but it'd be great to fix it, probably using Assembly.LoadFrom method rather than Assembly.Load(AssemblyName).

**Comment by jonorossi** [comment]
@rr-media it would be great if you could provide a pull request with a proposed fix, or at least a unit test.

**Comment by fir3pho3nixx** [comment]
Abandoned issue, closing.
