### ISSUE TITLE
WebService With DI

### ISSUE THREAD

**Issue by thinksjay** [castleproject/Windsor#317]
the web how to create web service with DI.
Sample：
public class AccountWebService : WebService, ITransientDependency
{
    private readonly ISessionAppService _sessionAppService;

    public AccountWebService (ISessionAppService sessionAppService)
    {
        _sessionAppService=sessionAppService;
    }
}

**Comment by jonorossi** [comment]
Hi, this is the Castle Windsor issue tracker, for help with your project please use [StackOverflow](http://stackoverflow.com/) (tagged with `castle-windsor`) or our users mailing list as per http://www.castleproject.org/get-involved/mailing-lists/.
