### ISSUE TITLE
Support NLog.Config API

### ISSUE THREAD

**Issue by davidshen84** [castleproject/Windsor#318]
Currently, Windsor logging facility for NLog only supports configure by configuration file.

NLog finally supports configuration, https://github.com/nlog/NLog/wiki/Configuration-API. I hope Windsor should support, so we can do:

    container.AddFacility<LoggingFacility>(facility => facility.UseNLog(NLogConfigInstance));

**Comment by jonorossi** [comment]
@davidshen84 it would be great if you could provide a pull request introducing this support, you'll likely also need to extend the Castle.Core NLog integration.

**Comment by davidshen84** [comment]
@jonorossi 

I tried to add NLog 4.4.1 Nuget dependency to `Castle.Facilities.Logging` project, but I got the following errors, when I try to build from VS and using the `build.cmd` tool.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0012	The type 'CLSCompliantAttribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.	Castle.Facilities.Logging(netstandard1.6)	C:\Users\david\github\Castle\Windsor\src\Castle.Facilities.Logging\CSC	1	Active
```

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS3001	Argument type 'LoggingConfiguration' is not CLS-compliant	Castle.Facilities.Logging(netstandard1.6)	C:\Users\david\github\Castle\Windsor\src\Castle.Facilities.Logging\LoggingFacility.cs	484	Active
```

But the `Castle.Services.Logging.NLogIntegration` project in the `Core` solution has the same dependency, and it build successfully on my machine.

**Can I get some help?**

Secondly, I found in the `NLogFactory.cs` in the `Castle.Services.Logging.NLogIntegration` project already has a factory overwrite that accepts `LoggingConfiguration`.

```public NLogFactory(LoggingConfiguration loggingConfiguration)```

So I think I do not need to modify the `Core`.

**Comment by jonnii** [comment]
I'm of the opinion that that is the wrong direction for Windsor. While log injection is incredibly useful it is trivial to with it up yourself with either a sub resolver or regular property injection. By creating logging abstractions you end up missing out on a lot of the power of using a specific logging framework (e.g. serilog).

**Comment by jonorossi** [comment]
@davidshen84 you shouldn't need to modify Windsor for this work since we've deprecated the built-in helpers for log4net and NLog, Windsor only cares about an `ILoggerFactory` and an `ILogger` now.

@jonnii agreed, however Windsor and other Castle projects need somewhere to log. Now that we've simplified things in Windsor around logging set up I think most of the pain should disappear.

I'm going to close this issue now that `UseNLog` is deprecated, you should be able to do something like:

```csharp
container.AddFacility<LoggingFacility>(f => f.LogUsing(new NLogFactory(loggingConfiguration)));
```
