### ISSUE TITLE
Error in Castle.Windsor

### ISSUE THREAD

**Issue by raji1908** [castleproject/Windsor#337]
Hi Everyone,

I have created a new class(Event Handler) to an existing service which worked fine in my local system but when I checked into my dev server faced an unusual error which effected entire application as below.

ServiceName: http://xxxxxxxxxxxxxxxxxxxxxxxx
Date Time: 9/13/2017 11:58:51 AM 
Fault Code: 1 
Description: ComponentActivator: could not instantiate (EventHandler created by me) 
Details: at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.CreateInstanceCore(ConstructorCandidate constructor, Object[] arguments, Type implType) in c:\BuildAgent\work\9834359f44c23fee\src\Castle.Windsor\MicroKernel\ComponentActivator\DefaultComponentActivator.cs:line 163 at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.CreateInstance(CreationContext context, ConstructorCandidate constructor, Object[] arguments) in c:\BuildAgent\work\9834359f44c23fee\src\Castle.Windsor\MicroKernel\ComponentActivator\DefaultComponentActivator.cs:line 116 at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.InternalCreate(CreationContext context) in c:\BuildAgent\work\9834359f44c23fee\src\Castle.Windsor\MicroKernel\ComponentActivator\DefaultComponentActivator.cs:line 66 at Castle.MicroKernel.ComponentActivator.AbstractComponentActivator.Create(CreationContext context, Burden burden) in c:\BuildAgent\work\9834359f44c23fee\src\Castle.Windsor\MicroKernel\ComponentActivator\AbstractComponentActivator.cs:line 80 at Castle.MicroKernel.Lifestyle.AbstractLifestyleManager.CreateInstance(CreationContext context, Boolean trackedExternally) in c:\BuildAgent\work\9834359f44c23fee\src\Castle.Windsor\MicroKernel\Lifestyle\AbstractLifestyleManager.cs:line 81 at Castle.MicroKernel.Lifestyle.AbstractLifestyleManager.Resolve(CreationContext context, IReleasePolicy releasePolicy) in c:\BuildAgent\work\9834359f44c23fee\src\Castle.Windsor\MicroKernel\Lifestyle\AbstractLifestyleManager.cs:line 70 at Castle.MicroKernel.Handlers.DefaultHandler.ResolveCore(CreationContext context, Boolean requiresDecommission, Boolean instanceRequired, Burden& burden) in c:\BuildAgent\work\9834359f44c23fee\src\Castle.Windsor\MicroKernel\Handlers\DefaultHandler.cs:line 148 at Castle.MicroKernel.Handlers.DefaultHandler.Resolve(CreationContext context, Boolean instanceRequired) in c:\BuildAgent\work\9834359f44c23fee\src\Castle.Windsor\MicroKernel\Handlers\DefaultHandler.cs:line 93 at Castle.MicroKernel.DefaultKernel.ResolveComponent(IHandler handler, Type service, IDictionary additionalArguments, IReleasePolicy policy) in c:\BuildAgent\work\9834359f44c23fee\src\Castle.Windsor\MicroKernel\DefaultKernel.cs:line 755 at Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.ResolveAll(Type service, IDictionary arguments, IReleasePolicy policy) in c:\BuildAgent\work\9834359f44c23fee\src\Castle.Windsor\MicroKernel\DefaultKernel_Resolve.cs:line 250 at Castle.Windsor.WindsorContainer.ResolveAll[T]() in c:\BuildAgent\work\9834359f44c23fee\src\Castle.Windsor\Windsor\WindsorContainer.cs:line 659 
Elapsed Time: 00:00:00.0312002 
Status: FAIL

Please let me know if anyone faced the same issue and how to resolve this?

Thanks in advance.

**Comment by fir3pho3nixx** [comment]
Hard to tell from the exception, can you post a repro?
