### ISSUE TITLE
Support for netcore 2.0

### ISSUE THREAD

**Issue by fir3pho3nixx** [castleproject/Windsor#356]
Would be great if we could think about implementing this. I have a project I would like to use it in :)

**Comment by jonorossi** [comment]
@fir3pho3nixx I'm confused, can't a .NET Standard 1.6 library be used on .NET Core 2.0? What has to be done here?

**Comment by wocar** [comment]
Same as @jonorossi  @fir3pho3nixx

**Comment by fir3pho3nixx** [comment]
Thought this would be a good place to start looking at the build symbols and what needs reworking similar to how the net45/net40 stuff was. 

Happy to close.
