### ISSUE TITLE
WCFFacility requires HTTP binding (when really just want HTTPS)

### ISSUE THREAD

**Issue by neutmute** [castleproject/Windsor#357]
I [posted a question](https://stackoverflow.com/questions/46728476/castle-windsor-wcffacility-service-has-zero-application-non-infrastructure-en) on StackOverflow but it didn't get any traction - so apologies for the cross post - thought I would try here.

The way the code in our project configures WCF Services with WCFFacility, an IIS HTTP binding is required even though I only want a HTTPS binding.

I'm sure we are doing something wrong in our codebase to cause this behaviour - any ideas?

StackOverflow has the details and a repro project.

**Comment by fir3pho3nixx** [comment]
Do you think you might find an answer in this? 

https://gist.github.com/hanssens/700862b3338866b092bf4c7dd4db691b

**Comment by neutmute** [comment]
No I don't think so - this is using a more generic binding and doesn't allow the security transport.

No matter, I've configured our deploys to add a spurious HTTP binding so it all works. It was very perplexing at the time but I've cut my losses and moved on. Let's close it off.
