### ISSUE TITLE
LifestylePerWebRequest missing

### ISSUE THREAD

**Issue by pirovorster** [castleproject/Windsor#359]
I instolled Castle.Windsor into my aspnet core application but LifestylePerWebRequest() is not available on

`Component.For<ISettingsService>().ImplementedBy<SettingsService>()`

I don't understand why?

**Comment by jonorossi** [comment]
`LifestylePerWebRequest` only supports `System.Web`, and `System.Web` functionality isn't available on .NET Core as documented in our [readme](https://github.com/castleproject/Windsor/blob/master/README.md#conditional-compilation-symbols).

There is work happening in #283 to bring ASP.NET Core support to Windsor, for now check out https://github.com/volosoft/castle-windsor-ms-adapter.

**Comment by blorger** [comment]
Documentation (https://github.com/castleproject/Windsor/blob/master/docs/mvc-tutorial-part-1-getting-windsor.md) was not properly updated for this breaking change.

**Comment by jonorossi** [comment]
@blorger no changes were made for this issue, the tutorial does not apply to .NET Core. If you are referring to the breaking changes in 5.0.0, then feel free to submit a pull request editing the tutorial.
