### ISSUE TITLE
CommonServiceLocator.WindsorAdapter NuGet package

### ISSUE THREAD

**Issue by karann-msft** [castleproject/Windsor#362]
This NuGet package currently does not have an owner. Given the description, and the fact that it lists @ayende as one of the authors, would you (@ayende), be interested in taking over ownership of this package?

[CommonServiceLocator.WindsorAdapter](https://www.nuget.org/packages/CommonServiceLocator.WindsorAdapter/)

**Comment by jonorossi** [comment]
It looks like @ayende provided the code to the CommonServiceLocator project back in 2008, and that code is still available on the Codeplex page. This wasn't/isn't a Castle project, I'd talk to those guys.

http://commonservicelocator.codeplex.com/wikipage?title=Castle%20Windsor%20Adapter&referringTitle=Home
