### ISSUE TITLE
Windsor Performance Counter miss in PerfMon using Windsor 4

### ISSUE THREAD

**Issue by scoppini** [castleproject/Windsor#365]
I would like to add the performance counter of windsor in my Performance Monitor... I have configured Windsor as indicated in your [docs](https://github.com/castleproject/Windsor/blob/master/docs/performance-counters.md) ...

`var diagnostic = LifecycledComponentsReleasePolicy.GetTrackedComponentsDiagnostic(container.Kernel);
var counter = LifecycledComponentsReleasePolicy.GetTrackedComponentsPerformanceCounter(new PerformanceMetricsFactory());
container.Kernel.ReleasePolicy = new LifecycledComponentsReleasePolicy(diagnostic, counter);`

Then I run my Web Api application, and I run the performance Monitor. But when I try to add a new counter I do not find the "Castle Windsor" section. 

What's wrong in what am I doing?

**Comment by jonorossi** [comment]
I've added the following answer to your StackOverflow question, let's continue there:

> It is likely Windsor doesn't have permission to create the performance counter category and counter (i.e. write to the registry) and is swallowing the `SecurityException` in `PerformanceMetricsFactory.Initialize`.
> 
> Run your application or Visual Studio elevated as administrator, you will only need to do this once.

(https://stackoverflow.com/questions/47416491/windsor-performance-counter-miss-in-perfmon)

I'll update our docs to include this info.
