### ISSUE TITLE
Register Component: Difference between .Parameters(Obsolete) and .DependsOn

### ISSUE THREAD

**Issue by dlazzarino** [castleproject/Windsor#368]
Hi all,
I'm trying to register programmatically a component with a static string parameter. Futhermore I have a custom LifeStyleManager that use this parameter in the "Init" method override. 

In a previous version of my code the component registration were made by xml configuration using the
element `<parameters>` and all worked fine. Ex:
`<parameters>
          <domain>MyDomain</domain>
</parameters>`

Now I'm trying to do the same programmatically, following the documentation I try with this code:
`.DependsOn(Dependency.OnValue("domain","MyDomain"))`
but, it doesn't work as expected because:
 - I'm able to read the parameter from my LifeStyleManager
 - When I try to resolve the component I get an exception of type "The component is waiting for a dependency $MyDomain...." 
It is strange, I want a string value, not a component.

Finally, I find a workaround using this code:
`.Parameters(Parameter.ForKey("domain").Eq("MyDomain"))` 
but this is an obsolete method. 

I prefer to find a real solution, any suggestion? What wrong?

Thx in advance

**Comment by jonorossi** [comment]
`DependsOn` takes a `Dependency` object. `Parameter`, `ServiceOverride` and `Property` instances are all implicitly convertible to a `Dependency` (they get wrapped to become a `Dependency`).

The static methods of `Dependency` make it easier to create one of these 3 objects, including:
- `Dependency.OnValue` creates a `Property` object, and is equivalent to `Property.ForKey(k).Eq(v)`, which results in being added to `ComponentModel.CustomDependencies`
- `Dependency.OnConfigValue` creates a `Parameter`, and is equivalent to `Parameter.ForKey(k).Eq(v)` , which results in being added to `ComponentModel.Configuration.Children`

I don't know why you are getting that error with `Dependency.OnValue` without more code and the full exception message.

**Comment by dlazzarino** [comment]
Hi @jonorossi ,
I have just tried with the `Dependency.OnConfigValue` and all works as expected  :-)

Probably I misunderstood the meaning of "OnConfigValue" with the concept of application config file.

Thanks a lot, 
you saved me a lot of time

Br
