### ISSUE TITLE
[Question/Suggestion] SelectInterceptorsWith should support injection

### ISSUE THREAD

**Issue by davidshen84** [castleproject/Windsor#369]
Neither of current implementation of `SelectInterceptorsWith` supports injection. Any particular reason? Or I just did not find the right one?

I think a `SelectInterceptorsWith<T>` would be nice.

**Comment by jonorossi** [comment]
Could you describe how you'd use this overload, I don't understand the question/request about injection.

**Comment by davidshen84** [comment]
```
container.
...
.Interceptors<Interceptor1>()
.SelectInterceptorWith<InterceptorSelector1>()
;
```

If the constructor of `InterceptorSelector1` has dependencies, it would allow the kernel to inject the dependencies.

**Comment by jonorossi** [comment]
Doesn't the second overload allow you to do that.

```
public ComponentRegistration<TService> SelectInterceptorsWith(Action<ItemRegistration<IInterceptorSelector>> selector)
```

```
Container.Register(Component.For<IMyService>()
    .ImplementedBy<MyComponent>()
    .SelectInterceptorsWith(s => s.Service<MyInterceptorSelector>()));
```

**Comment by davidshen84** [comment]
Yes, it does. Thanks :)
