### ISSUE TITLE
FIPS Compliance?

### ISSUE THREAD

**Issue by AlNistor** [castleproject/Windsor#370]
Hi,
I'm using this library for a project that has to be FIPS Compliant, but when I enabled FIPS on my windows machine, I get an exception that:
` InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.`
May I ask why isn't it FIPS compliant? What encryption algorithms do you use?

**Comment by jonorossi** [comment]
> May I ask why isn't it FIPS compliant? What encryption algorithms do you use?

Please include the exception's stack trace so we can see where this is occurring. About the only thing Windsor uses crypto for is X509 certificates in the WCF facility.

**Comment by AlNistor** [comment]
Oh, my bad.
I was using an SDK from [Wibu](https://www.wibu.com/) and instantiating it using windsor. That was causing the error for FIPS compliance. As soon as I was instantiating a class from Wibu in one of my services I would get the posted Exception.
Sorry for disturbing. You can close/delete this thread. 😄
