### ISSUE TITLE
Can't find Castle.Facilities.AspNetCore nuget package in nuget gallery

### ISSUE THREAD

**Issue by buddalasunil999** [castleproject/Windsor#393]
![image](https://user-images.githubusercontent.com/2284522/38596914-7f3a60c0-3da8-11e8-81ec-23aab2852ee8.png)

The documentation says I can find the "Castle.Facilities.AspNetCore" nuget but no such package exists in nuget.

![image](https://user-images.githubusercontent.com/2284522/38596962-c2127bbc-3da8-11e8-8707-9453cb6fed17.png)

**Comment by jonorossi** [comment]
You are reading the docs for the `master` branch, those are unreleased changes.

**Comment by buddalasunil999** [comment]
oh okay. is there a pr-release of this?

**Comment by jonorossi** [comment]
You could get the packages from our build server:

- https://ci.appveyor.com/project/castleproject/windsor/history
- https://ci.appveyor.com/nuget/windsor-qkry8n2r6yak

**Comment by fir3pho3nixx** [comment]
Please be sure to note:

 - The latest version is here: https://github.com/fir3pho3nixx/Windsor/tree/aspnet-core-windsor-final

It supports the razor directive @inject but comes with the cost of a memory leak. I am thinking of disabling the razor inject by default for v5. It is lethal when it comes to memory management ....

**Comment by buddalasunil999** [comment]
when is the next version releasing?

**Comment by fir3pho3nixx** [comment]
We are in the process of reviewing the final PR here: https://github.com/castleproject/Windsor/pull/394

We will release as soon as it makes it into master I think...

**Comment by fir3pho3nixx** [comment]
If you follow the CastleProject on twitter you will know as soon as have released.

**Comment by fir3pho3nixx** [comment]
If you want a cut of it now, you can use our build artifacts here: https://ci.appveyor.com/project/castleproject/windsor/build/0.0.384/artifacts

You have raised something crucial though, We don't actually have a `can I has it now` documentation page. I will raise an issue in Windsor and tag you.

**Comment by buddalasunil999** [comment]
sweet, thank you :-)

**Comment by rohan3usturge** [comment]
Hi Team,

Thanks for creating this.

I wanted to use this library in a Production App. Is this nuget going to be released anytime soon ?

**Comment by jonorossi** [comment]
@rohan3usturge I recommend following #418.
