### ISSUE TITLE
Case sensitive component registration

### ISSUE THREAD

**Issue by zamojski** [castleproject/Windsor#399]
I faced an issue related to case insensitive component registration. Unfortunately I had to spend an hour to figure it out myself because such, in my opinion important information, is not available anywhere in the docs.

Having two components with the same names but different letter casing it's not possible to register them in WindsorContainer because it throws an exception `Component XXX could not be registered. There is already a component with that name. Did you want to modify the existing component instead? If not, make sure you specify a unique name.`. Unfortunately I cannot change the names of these components. 

As a workaround I found a class `DefaultNamingSubSystem` which declares `protected readonly Dictionary<string, IHandler> name2Handler = new Dictionary<string, IHandler>(StringComparer.OrdinalIgnoreCase);` which I'd like to inherit from and overwrite the dictionary type with `StringComparer.Ordinal`. Unfortunately this property is readonly so I need to copy & paste whole class which is a bad practice on longer term. I'm also not sure if this will cover all the possible cases and won't break the internal Windsor logic.

Please advise what else can I do to make Windsor Container case sensitive.

**Comment by mario-d-s** [comment]
> Unfortunately I cannot change the names of these components.

Please clarify. Your whole issue is screaming [XY problem](https://en.wikipedia.org/wiki/XY_problem) to me. Why would you want to register named components when you have no control over the name? Why would casing be important in any scenario?

**Comment by zamojski** [comment]
To be precise in my case naming conflict comes out in result of code obfuscation which I cannot control. The classes are internal so the names get encrypted and shortened to just a few characters. It happens that the new names differ only by letter casing and those conflicted are all registered in Castle Windsor. Please consider the following code as an example - it fails on installation.

```
public class CastlE : ICastlE
{
}

public class Castle : ICastle
{
}

public interface ICastle
{
}

public interface ICastlE
{
}

public class CastleInstaller : IWindsorInstaller
{
    public void Install(IWindsorContainer container, IConfigurationStore store)
    {
        container.Register(Component.For<ICastle>().ImplementedBy<Castle>());
        container.Register(Component.For<ICastlE>().ImplementedBy<CastlE>());
    }
}

public class Program
{
    public static void Main()
    {
        var container = new WindsorContainer();
        // TODO: possible workaround but whole class needs to be copied (to keep behavior) because name2Handler field is readonly
        // TODO: container.Kernel.AddSubSystem(SubSystemConstants.NamingKey, new CaseSensitiveNamingSubSystem()); 
        container.Install(new CastleInstaller());

        container.Resolve<ICastle>();
        container.Resolve<ICastlE>();
    }
}
```

**Comment by mario-d-s** [comment]
> To be precise in my case naming conflict comes out in result of code obfuscation which I cannot control. The classes are internal so the names get encrypted and shortened to just a few characters.

This way of working sounds alarming to me. Code obfuscation is a compilation step but as a developer you should definitely be able to work with nicely named classes. I'd absolutely **hate** to work in a project that even has classes that only differ by casing.

Nevertheless, I see a valid issue here in that you don't explicitly use naming and the installer still fails. It'll be up to the project maintainers though to decide whether anything will be done. In the meantime... I suggest you pursue more sane coding circumstances.

**Comment by zamojski** [comment]
The issues comes out of obfuscation but I cannot turn off due to intellectual property protection requirement. On the other hand I don't want to create custom Castle Windsor compilation or copy classes just to overcome the issue. This should be a part of configuration in my opinion.

**Comment by fir3pho3nixx** [comment]
@zamojski do you think you put a PR together with a test that exposes the problem? Would be happy to have a quick look.

**Comment by fir3pho3nixx** [comment]
Thanks will have a look tonight

**Comment by fir3pho3nixx** [comment]
What you are asking for is simple but it breaks things. Would need your help with the failing tests @ https://github.com/fir3pho3nixx/Windsor/tree/windsor_400

**Comment by fir3pho3nixx** [comment]
Please re-open when you have new intel.

**Comment by zamojski** [comment]
I would like to propose a small change which should not break existing logic but will open the way to customize without creating completely new `DefaultNamingSubSystem` (or copying existing). As I already mentioned in first post removing `readonly` keyword from `name2Handler` declaration would help us a lot.

**Comment by fir3pho3nixx** [comment]
That could be possible.

I am a little alarmed by the fact that this test case is failing:

```csharp
[Test]
public void TransientReferencesAreNotHeldByContainer()
{
	Kernel.Register(Component.For<EmptyClass>().LifeStyle.Transient);
	var emptyClassWeakReference = new WeakReference(Kernel.Resolve<EmptyClass>());

	GC.Collect();
	GC.WaitForPendingFinalizers();

	Assert.IsFalse(emptyClassWeakReference.IsAlive);
}
```

![image](https://user-images.githubusercontent.com/607402/40378543-c5dd9246-5deb-11e8-999f-077a34f152ce.png)

Have you checked to make sure that by doing this you are not leaking memory? Danger!
