### ISSUE TITLE
Some source code string literals are not utf-8

### ISSUE THREAD

**Issue by davidshen84** [castleproject/Windsor#405]
When trying to compile Windor on non-English platform, say Chinese, I got compilation errors that are caused by unrecognizable characters.

```
-			Assert.AreEqual("GenericHasNested< TOuter >.NestedGeneric<A2, AProp>[,,]", name);
+			Assert.AreEqual("GenericHasNested<·TOuter·>.NestedGeneric<A2, AProp>[,,]", name);
```

It turns out the file is not in utf-8 encoding. It would be nice if we save all source files in utf-8 encoding.

BTW, what is that `·` for?

**Comment by jonorossi** [comment]
Fixed in #407.
