### ISSUE TITLE
Support for .net core generic hosts

### ISSUE THREAD

**Issue by generik0** [castleproject/Windsor#412]
Is there a need to create a facility or other to support .net core 2.1+ generic host.
Castle may need a e.g. ServiceProviderFacility that is used by bot the aspnetcore facility and used by the generic host "UseServiceProviderFactory"

[.net core generic host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.1)

E.g.
```c#
var host = new HostBuilder()
                .UseServiceProviderFactory(new CastleServiceProviderFactory())
                .ConfigureContainer<IWindsorContainer>(hostContext, container) =>
                {
                                //Register Special Stuff
                })
                .Build();
```

**Comment by mbp** [comment]
That would be great. Right now I use this: https://github.com/volosoft/castle-windsor-ms-adapter/blob/master/src/Castle.Windsor.MsDependencyInjection/WindsorServiceProviderFactory.cs

But if that library is being replaced by Windsor 5, I suppose we need this factory here as well.

**Comment by jonorossi** [comment]
Closing as stale. `Castle.Windsor.Extensions.DependencyInjection` is the path forward for ASP.NET Core 3.x.

**Comment by generik0** [comment]
@jonorossi this is solved with latest DependencyInjection implementation. Thanks.
