### ISSUE TITLE
WcfFacility's WcfClientExtension.AddChannelBuilder doesn't appear to work

### ISSUE THREAD

**Issue by biltongza** [castleproject/Windsor#419]
Given the following:

    private void RegisterService<T>(IWindsorContainer container, string serviceName)
            where T : class
        {
            var serviceSettings = new ServiceSettings(serviceName);
            var binding = new WS2007FederationHttpBinding(WSFederationHttpSecurityMode.TransportWithMessageCredential);
            binding.Security.Message.EstablishSecurityContext = false;
            binding.Security.Message.IssuedKeyType = System.IdentityModel.Tokens.SecurityKeyType.BearerKey;
            var endpoint = WcfEndpoint.BoundTo(binding).At(serviceSettings.Endpoint).AddExtensions(new WcfClientExtension().AddChannelBuilder<BearerTokenChannelBuilder>());
            var clientModel = new SecureWcfClientModel(endpoint);
            container.Register(Component.For<T>().AsWcfClient(clientModel));
        }

        public class BearerTokenChannelBuilder : AbstractChannelBuilder<SecureWcfClientModel>
        {
            private ITokenGetter tokenGetter;

            public BearerTokenChannelBuilder(IKernel kernel, IChannelFactoryBuilder<SecureWcfClientModel> channelFactoryBuilder, ITokenGetter tokenGetter)
                : base(kernel, channelFactoryBuilder)
            {
                this.tokenGetter = tokenGetter;
            }

            protected override ChannelCreator CreateChannelCreator(Type contract, SecureWcfClientModel clientModel, IChannelBuilderScope scope, params object[] channelFactoryArgs)
            {
                var type = typeof(ChannelFactory<>).MakeGenericType(new[] { contract });
                var channelFactory = this.ChannelFactoryBuilder.CreateChannelFactory(type, clientModel, channelFactoryArgs);
                scope.ConfigureChannelFactory(channelFactory);

                var methodInfo = type.GetMethod("CreateChannelWithIssuedToken", new Type[] { typeof(SecurityToken) });
                ChannelCreator creator = new ChannelCreator(() =>
                {
                    return methodInfo.Invoke(channelFactory, new[] { this.tokenGetter.GetToken() });
                });
                return creator;
            }
        }

        public class SecureWcfClientModel : WcfClientModel<SecureWcfClientModel>
        {
            public SecureWcfClientModel()
            {
            }

            public SecureWcfClientModel(IWcfEndpoint endpoint) 
                : base(endpoint)
            {
            }
        }

        public interface ITokenGetter
        {
            SecurityToken GetToken();
        }

        public class TokenGetter : ITokenGetter
        {
            public SecurityToken GetToken()
            {
                throw new NotImplementedException();
            }
        }

When I try use a WCF service with my configuration like this, I get 

    No component for supporting the service Castle.Facilities.WcfIntegration.IChannelBuilder`1[[SecureWcfClientModel, AssemblyNameHere, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] was found

However, if I manually register the builder like so:

    container.Register(Component.For<IChannelBuilder<SecureWcfClientModel>>().ImplementedBy<BearerTokenChannelBuilder>());

Then it works and I get my `NotImplementedException` as expected.

Am I missing something?

**Comment by biltongza** [comment]
Fixed it with this:

    container.AddFacility<WcfFacility>(c => c.Clients.AddChannelBuilder<BearerTokenChannelBuilder>());

**Comment by fir3pho3nixx** [comment]
@biltongza 

Welcome(I am a fellow country man). Closing as you appear to have fixed the problem.
