### ISSUE TITLE
Test fail when run using Visual Studio 15.7.5 and Resharper 2018.1.3 but not from build.cmd for net45

### ISSUE THREAD

**Issue by fir3pho3nixx** [castleproject/Windsor#421]
When running test inside Visual Studio using Resharper I noticed that 13 tests are failing. However when I run the test from `build.cmd` everything passes. I just updated my Visual Studio and Resharper today and noticed this to be the case. 

![image](https://user-images.githubusercontent.com/607402/42726947-150c837c-8795-11e8-8cf5-50e18b8466bb.png)

![image](https://user-images.githubusercontent.com/607402/42726951-1dc26d92-8795-11e8-844a-75632e31c659.png)

**Comment by fir3pho3nixx** [comment]
An example of a test that fails is:

https://github.com/castleproject/Windsor/blob/81fbdf084d3b6e235ff54c4f29bbc8d93fd408ec/src/Castle.Windsor.Tests/Lifecycle/DisposeTestCase.cs#L95-L112

`Assert.IsFalse(weak.IsAlive);` appear to be having a problem.

**Comment by jonorossi** [comment]
Did you have dotMemory and dotTrace installed before this started failing? I've run the tests with them installed before but maybe something has changed with their instrumentation that is causing the short lived objects not to get garbage collected when asked.

Could you try some of the suggestions in this StackOverflow thread to see what fixes it:
https://stackoverflow.com/questions/15205891/garbage-collection-should-have-removed-object-but-weakreference-isalive-still-re

**Comment by fir3pho3nixx** [comment]
@jonorossi You are right. Today I started profiling some integration tests on another project and file locks were kicking in and failing tests. I will re-post this on the JB issue tracker.

**Comment by fir3pho3nixx** [comment]
The answer is upgrade, and upgrade often. Works for ... 

![image](https://user-images.githubusercontent.com/607402/44485446-796f6600-a648-11e8-9e7d-13981609618f.png)

![image](https://user-images.githubusercontent.com/607402/44485460-88eeaf00-a648-11e8-8a55-35f3c4d0a5ee.png)

**Comment by mario-d-s** [comment]
@fir3pho3nixx I'm afraid it doesn't. Maybe related to some setting (in VS or R#), or installed components?

I have the exact same versions in either case.

**Comment by fir3pho3nixx** [comment]
Are you opening the solution with elevated privileges? Which tests are failing for you?

**Comment by mario-d-s** [comment]
> Are you opening the solution with elevated privileges?

I am. My Visual Studio is set to *always run as Administrator*. Now that I mention it: **I am on 2017 Professional** whereas you are using Community.

> Which tests are failing for you?

13 tests, so assuming the same ones as did for you earlier.
TXT export of the run [here](https://gist.github.com/mario-d-s/3edaa2c8b9ebd7d90ed29ef57ab68583).

**Comment by fir3pho3nixx** [comment]
@mario-d-s 

Have you taken the latest updates from Visual Studio? Quite a few got barreled out over the past few days.

**Comment by mario-d-s** [comment]
@fir3pho3nixx I just did, still 13 tests are failing. I'm thinking this must be related to the compiler. For example I have the .NET 4.7.2 SDK installed and these are the properties of CSC.exe:

![CSC.exe properties](https://user-images.githubusercontent.com/4290238/44900581-39be1380-ad05-11e8-83bc-245029186522.png)

**Comment by fir3pho3nixx** [comment]
@mario-d-s can you please try with the latest VS/RS updates and tell me if anything changes? I have not seen any problems.

**Comment by fir3pho3nixx** [comment]
Marking this as abandoned. I don't have this issue at work or on BYOD.

**Comment by jnm2** [comment]
Reproing on VS 15.8.7 and ReSharper 2018.2.3 which are current as of today.

In every case, the problem is that the `WeakReference` the test creates is alive when the test expects it not to be.

In particular, this trivial test (which follows the same pattern that the real tests depend on) fails:

```c#
		[Test]
		public void Test()
		{
			var weak = new WeakReference(new object());
			GC.Collect();
			Assert.IsFalse(weak.IsAlive);
		}
```

Therefore, all the real tests have some hidden assumptions about the timeframe in which GC will certainly happen. There should probably be a test helper which actually ensures GC.

**Comment by jnm2** [comment]
Discovered that the problem disappears when the solution configuration is switched to Release. In Debug, this test never completes. In Release, it completes instantly:

```c#
			var weak = new WeakReference(new object());

			while (weak.IsAlive)
			{
				GC.Collect();
			}
```

**Comment by jnm2** [comment]
In Debug mode, this is the IL:

```
  .method public hidebysig instance void 
    SimpleRepro() cil managed 
  {
    .custom instance void [nunit.framework]NUnit.Framework.TestAttribute::.ctor() 
      = (01 00 00 00 )
    .maxstack 1
    .locals init (
      [0] class [mscorlib]System.WeakReference weak
    )

    IL_0000: nop          

    IL_0001: newobj       instance void [mscorlib]System.Object::.ctor()
    IL_0006: newobj       instance void [mscorlib]System.WeakReference::.ctor(object)
    IL_000b: stloc.0      // weak

    IL_000c: call         void [mscorlib]System.GC::Collect()
    IL_0011: nop          

    IL_0012: ldloc.0      // weak
    IL_0013: callvirt     instance bool [mscorlib]System.WeakReference::get_IsAlive()
    IL_0018: call         void [nunit.framework]NUnit.Framework.Assert::IsFalse(bool)
    IL_001d: nop          

    IL_001e: ret          
  }
```

Release mode uses the evaluation stack instead of storing and loading from a local:
```
  .method public hidebysig instance void 
    SimpleRepro() cil managed 
  {
    .custom instance void [nunit.framework]NUnit.Framework.TestAttribute::.ctor() 
      = (01 00 00 00 )
    .maxstack 8

    IL_0000: newobj       instance void [mscorlib]System.Object::.ctor()
    IL_0005: newobj       instance void [mscorlib]System.WeakReference::.ctor(object)

    IL_000a: call         void [mscorlib]System.GC::Collect()

    IL_000f: callvirt     instance bool [mscorlib]System.WeakReference::get_IsAlive()
    IL_0014: call         void [nunit.framework]NUnit.Framework.Assert::IsFalse(bool)

    IL_0019: ret          
  }
```

**Comment by jnm2** [comment]
ReSharper is behaving as you'd expect for a .NET assembly compiled in debug mode. You'd get the same behavior if the test was a console app. The oddball is VSTest; these tests wouldn't normally pass if the project is compiled in debug mode.

Good answer here: https://stackoverflow.com/questions/37462378/why-c-sharp-garbage-collection-behavior-differs-for-release-and-debug-executable

**Comment by jnm2** [comment]
What works is this pattern, never evaluating the expression that returns the tracked instance within the method but rather within a call that returns:

```cs
		[Test]
		public void Managed_externally_factory_component_transient_is_not_tracked_by_the_container()
		{
			Kernel.Register(Component.For<DisposableComponent>()
			                	.LifeStyle.Transient
			                	.UsingFactoryMethod(() => new DisposableComponent(), managedExternally: true));

			var weak = GetWeakReferenceForTesting(Kernel.Resolve<DisposableComponent>());
			GC.Collect();

			Assert.IsFalse(weak.IsAlive);
		}

		private static WeakReference GetWeakReferenceForTesting(Func<object> getInstanceToTrack)
		{
			return new WeakReference(getInstanceToTrack.Invoke());
		}
```

**Comment by jnm2** [comment]
Hey, while refactoring all the WekReference tests to use a new helper API, I discovered that @ivan-danilov had run into (and documented) this exact same issue on a single test:

https://github.com/castleproject/Windsor/blob/07e4b667c1826decdba1724642d6d68c2080c64e/src/Castle.Windsor.Tests/Lifestyle/ScopedLifestyleTestCase.cs#L179-L201

See https://github.com/castleproject/Windsor/pull/138 for that pull request.

**Comment by jnm2** [comment]
This exact issue was also discovered on two other tests by @alinapopa and discussed here: https://github.com/castleproject/Windsor/pull/235#discussion_r117166843

https://github.com/castleproject/Windsor/blob/07e4b667c1826decdba1724642d6d68c2080c64e/src/Castle.Facilities.WcfIntegration.Tests/Client/WcfClientFixture.cs#L268-L272

https://github.com/castleproject/Windsor/blob/07e4b667c1826decdba1724642d6d68c2080c64e/src/Castle.Facilities.WcfIntegration.Tests/Client/WcfClientFixture.cs#L351-L355
