### ISSUE TITLE
WindsorRegistrationExtensions.AddApplicationComponentsToWindsor

### ISSUE THREAD

**Issue by MAliM1988** [castleproject/Windsor#423]
Hi Everyone

in this Method I Have Problem For Registering `ControllerBase` For Registering Api Controller in asp Net Core 2.1

in this Method you Use this Code 

```
foreach (var controllerRegistration in options.ControllerRegistrations)
{
	container.Register(Classes.FromAssemblyInThisApplication(controllerRegistration.Item1).BasedOn<Controller>().Configure(x => x.LifeStyle.Is(controllerRegistration.Item2)));
}
```

And Ignore `ControllerBase` Type,I Use this Code For Fix this Problem

```
foreach (var controllerRegistration in options.ControllerRegistrations)
{
	//container.Register(Classes.FromAssemblyInThisApplication(controllerRegistration.Item1).BasedOn<Controller>().Configure(x => x.LifeStyle.Is(controllerRegistration.Item2)));
	container.Register(Classes.FromAssemblyInThisApplication(controllerRegistration.Item1).BasedOn<ControllerBase>().Configure(x => x.LifeStyle.Is(controllerRegistration.Item2)));
}
```

**Comment by fir3pho3nixx** [comment]
https://github.com/castleproject/Windsor/blob/master/docs/aspnetcore-facility.md#registering-controllers-viewcomponents-and-taghelpers

```csharp
services.AddWindsor(container, opts =>
{
	opts.RegisterControllers(typeof(HomeController).Assembly, LifestyleType.Transient);
	opts.RegisterTagHelpers(typeof(EmailTagHelper).Assembly, LifestyleType.Transient);
	opts.RegisterViewComponents(typeof(AddressComponent).Assembly, LifestyleType.Transient);
});
```
[WindsorRegistrationOptions](https://github.com/castleproject/Windsor/blob/master/src/Castle.Facilities.AspNetCore/WindsorRegistrationOptions.cs#L25) was meant to be the way of overriding defaults used for registration. Do you think we should expose the [component registration](https://github.com/castleproject/Windsor/blob/master/src/Castle.Windsor/MicroKernel/Registration/Component.cs#L33) api's here so we gain maximum flexibility?

Something like:

 ```csharp
services.AddWindsor(container, opts =>
{
	opts.RegisterControllers(Classes.FromAssemblyInThisApplication(options.EntryAssembly).BasedOn<ControllerBase>().LifestyleScoped());
});
```

Also I think scanning for anything based on [ControllerBase](https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/ControllerBase.cs) might be a more sensible default. Please feel free to submit a PR for this change.

**Comment by fir3pho3nixx** [comment]
//cc https://github.com/castleproject/Windsor/issues/423

**Comment by MAliM1988** [comment]
Hi 
Thanks for your suggest

**Comment by fir3pho3nixx** [comment]
Yup, code is wrong. Could definitely be improved as you say. Instead of doing it as an additive change we should probably replace the existing API.

Do you want to have a go at submitting this PR before we release? If not I am happy to pick this up, I would need help reviewing it though.

**Comment by MAliM1988** [comment]
how can I Add Pr Before Your Release ?

**Comment by fir3pho3nixx** [comment]
@MAliM1988 

Please take a look at this commit. This is what I mean't to change. 

https://github.com/fir3pho3nixx/Windsor/commit/14ad698c7df4eec8fa7c231807a622467e2bec11

You should be able to do this now.

```csharp
services.AddWindsor(container, opts =>
{
opts.RegisterControllers(Classes.FromAssemblyInThisApplication(options.EntryAssembly).BasedOn<ControllerBase>().LifestyleScoped());
});
```

I am going to keep this on the https://github.com/fir3pho3nixx/Windsor/tree/aspnet-core-facility-vnext branch for now as you have closed the issue.

**Comment by MAliM1988** [comment]
Hi @fir3pho3nixx

Thanks for your commit,this Commit is Great but i think you should add a new Method for registering type of `IRegistration` Members on `WindsorRegistrationOptions` And Save your old Code as default for Controller Registeration on `ControllerBase` in

```
foreach (var controllerRegistration in options.ControllerRegistrations)
{
	container.Register(Classes.FromAssemblyInThisApplication(controllerRegistration.Item1).BasedOn<ControllerBase>().Configure(x => x.LifeStyle.Is(controllerRegistration.Item2)));
}
```

Your new commit can be new feature on  `WindsorRegistrationOptions` for registering other implementation of `IRegistration` and handling Custom Type of Controller.

Thanks for Your Answer and Commit.

**Comment by fir3pho3nixx** [comment]
You re-opened, cool, so you want us to target our initial release with these changes? Could you kindly submit a PR?

**Comment by MAliM1988** [comment]
Hi

I submit another PR for this change?

Thanks

**Comment by fir3pho3nixx** [comment]
Yes please, 

1. We change the Controller reference [here](https://github.com/castleproject/Windsor/blob/master/src/Castle.Facilities.AspNetCore/WindsorRegistrationExtensions.cs#L98) to ControllerBase
2. [This](https://github.com/castleproject/Windsor/blob/master/src/Castle.Facilities.AspNetCore/WindsorRegistrationExtensions.cs#L103) might also need to change to ControllerBase. 
3. In addition to the [RegisterControllers](https://github.com/castleproject/Windsor/blob/master/src/Castle.Facilities.AspNetCore/WindsorRegistrationOptions.cs#L70) should we add the additional IRegistration overload as I have done [here](https://github.com/fir3pho3nixx/Windsor/commit/14ad698c7df4eec8fa7c231807a622467e2bec11#diff-dfcbe92039817c0915a22cbbf4642a38R70)?

What do you think?

**Comment by fir3pho3nixx** [comment]
We still have time before we release. I still have some work to do on V5 deprecation work to do.

**Comment by MAliM1988** [comment]
Hi @fir3pho3nixx 

I add PR today

Thank alot

**Comment by fir3pho3nixx** [comment]
It looks like you raised a PR that attempts to merge the typed-factories branch into master. It this what you meant?

**Comment by MAliM1988** [comment]
Hi

I can't add on master branch PR

**Comment by fir3pho3nixx** [comment]
@MAliM1988 

This PR fixes this issue: https://github.com/castleproject/Windsor/pull/432

Please notice the code change for registering controllers as ControllerBase [here](https://github.com/castleproject/Windsor/pull/432/files#diff-77a22f5542ffd29a9b211c43bfb976f3R100). 

I also found that TagHelpers were not being registered with the interface [here](https://github.com/castleproject/Windsor/pull/432/files#diff-77a22f5542ffd29a9b211c43bfb976f3R110).

**Comment by fir3pho3nixx** [comment]
Can we close this issue?

**Comment by fir3pho3nixx** [comment]
Fixed via #432.

**Comment by MAliM1988** [comment]
Hi @fir3pho3nixx 

Thanks for new commit.
I hope your new version release soon.

thanks alot

**Comment by fir3pho3nixx** [comment]
Good stuff mate, you brought us closer to the framework and gave some hints for doing things better. 

My constructive criticism towards this experience was that perhaps you should learn how github works. You raised 2 invalid PR’s, did not commit any code. If you need some help I can guide you with some links. 

Your input none the less was invaluable, so thank you 🙏🏻

**Comment by MAliM1988** [comment]
Hi @fir3pho3nixx 

I'm new user on git and I'm not very fluent in using Git, and so I had a mistake in registering a PR on the project,sorry for that and yes please guide me with some links.

thanks a lot @fir3pho3nixx

**Comment by fir3pho3nixx** [comment]
Are you using Windows? If so, get yourself a GUI to start, it visually helps you discover new features to google. I would recommend using something like [tortoisegit](https://tortoisegit.org/). There are some really cool [GUI's](https://git-scm.com/downloads/guis/) to choose from otherwise. 

As for GitHub and PR's. Please explore the following links and let me know how you get on.

 - https://help.github.com/articles/fork-a-repo/
 - https://help.github.com/articles/creating-a-pull-request-from-a-fork/
 - https://help.github.com/categories/collaborating-with-issues-and-pull-requests/ :)

**Comment by fir3pho3nixx** [comment]
To install git bash you would need to install [this](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git).
