### ISSUE TITLE
Introduce IContributeComponentRegistrationConstruction

### ISSUE THREAD

**Issue by augi** [castleproject/Windsor#46]
If I want to write some _cross-cutting_ registration then I can use _IContributeComponentModelConstruction_ interface that works over _ComponentModel_.
It's absolutely sufficient for primitive registrations but if I want to make some complex stuff then I would like to re-use nice methods (eg. _DependOn_) available on _ComponentRegistration<T>_ class.

So it would be nice to be able to alter _ComponentRegistration_ just before _ComponentModel_ is built.

I would be able to register my implementations of _IContributeComponentRegistrationConstruction_ that would be probably called from _DefaultKernel.Register()_ method.
The the interface could work over _IRegistration_, but just for _ComponentRegistration_ would makes sense too for me.

**Comment by jonorossi** [comment]
Closing this for now as no examples were provided and `IContributeComponentModelConstruction` does the job.
