### ISSUE TITLE
How Can I Use IOptions<T> With Castle

### ISSUE THREAD

**Issue by MAliM1988** [castleproject/Windsor#463]
Hi everyone

I Use Castle in my Asp.net Core project and use this for reading option from appsetting.json

`services.Configure<PermissionOptions>(Configuration.GetSection("PermissionOptions"));`

but i can't resolve ` IOptions<PermissionOptions>` into my service for use,how can i fix this?
 thanks .

**Comment by dquist** [comment]
What version of ASP.NET Core?

Are you using the Windosr AspNetCore facility?

**Comment by jonorossi** [comment]
Closing as stale. `Castle.Windsor.Extensions.DependencyInjection` is the path forward for ASP.NET Core 3.x.
