### ISSUE TITLE
ASP.NET Core Facility Package

### ISSUE THREAD

**Issue by MAliM1988** [castleproject/Windsor#467]
Hi everyone

Why ASP.NET Core Facility Package Not In Nuget Package Management After New Release of CastleWindsor ?
I Think Asp Net Core Facility Release With Castle Windsor 5.0

**Comment by jonorossi** [comment]
Can you please be more specific.

The following web page shows 5.0.0 already has 24 downloads:
https://www.nuget.org/packages/Castle.Facilities.AspNetCore/

**Comment by MAliM1988** [comment]
thanks
