### ISSUE TITLE
High CPU 

### ISSUE THREAD

**Issue by colby02184** [castleproject/Windsor#469]
We converted from Structure Map and are experiencing high CPU issues when we went to production. Nothing except the IoC framework changed. CPU  comsumption was not a problem with Structureap. We strictly implemented the resolve release pattern that's meantioned in the docs. Our lifestyles is transient for all components and services.  Has anyone seen this sort of thing?

**Comment by jnm2** [comment]
I've been a using it for a number of years and have not seen CPU issues yet. Can you provide a repro project?

**Comment by colby02184** [comment]
Not at the moment but I will put one together and put it up. Our Web app is a mix of webforms and MVC 5. We do Resolve components in our webforms side of things but we control that resolution and immediately release the component from the Kernel. Our controllers are fairly heavy in they take 6-7 parameters but Structure Map handled that without issue. I'm really at a loss in what I'm doing wrong with Windsor.

**Comment by jonorossi** [comment]
@colby02184 as @jnm2 has already said you'll need to provide a full running repro for someone else to have any chance of working out the problem, or better yet use a profiling tool like dotTrace which should help you find your problem quickly.

I'm going to close this issue for now until we've got something to action (please reopen when you've got more info) because there are no known issues that cause high CPU usage.

**Comment by mario-d-s** [comment]
You did say all your components are transient, so that means every dependency is getting reconstructed all the time, was that your setup with StructureMap as well?

Jonorossi has the best idea of using a profiler which aside from a repro will give maintainers some actionable insight.

**Comment by colby02184** [comment]
Just the default which is transient. But it seems like structure maps implementation of transient it's like Windsor's perwebrequet. 

http://structuremap.github.io/object-lifecycle/supported-lifecycles

**Comment by mario-d-s** [comment]
@colby02184 actually, the default in Windsor is singleton... And per web request means if you're resolving some component twice within the same request, it will appear as singleton, while you will get back different instances in different requests.

**Comment by colby02184** [comment]
@mario-d-s thank you for the clarification on the perwebrequet lifestyle and yes I knew Windsor's defay is Singleton and  due to the fact I control component registration in a common project that's shared across all projects -- by control I mean I set registrations to transient. 

Btw which lifestyle is recommended with an MVC mixed with a Webforms application?
