### ISSUE TITLE
AspNetCoreFacility: Add CollectionResolver to documentation

### ISSUE THREAD

**Issue by jirikanda** [castleproject/Windsor#471]
In the AspNetCoreFacility documentation there is quite complex example how to setup the project with Windsor Castle.
To make it working the CollectionResolver should be added:
```c-sharp
container.Kernel.Resolver.AddSubResolver(new CollectionResolver(container.Kernel, allowEmptyCollections: true));
```
Otherwise, the following demo will not work (but it works well without Castle Windsor and AspNetCoreFacility).
```c-sharp
using Castle.Facilities.AspNetCore;
using Castle.MicroKernel.Registration;
using Castle.MicroKernel.Resolvers.SpecializedResolvers;
using Castle.Windsor;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;

namespace MyWebApplication
{
	public class Program
	{
		public static void Main(string[] args)
		{
			WebHost.CreateDefaultBuilder(args).UseStartup<Startup>().Build().Run();
		}
	}

	public class Startup
	{
		private static IWindsorContainer container = new WindsorContainer();

		public IServiceProvider ConfigureServices(IServiceCollection services)
		{
			// container.Kernel.Resolver.AddSubResolver(new CollectionResolver(container.Kernel, allowEmptyCollections: true)); // when uncommented the demo works again

			container.AddFacility<AspNetCoreFacility>(f => f.CrossWiresInto(services));
			services.AddMvc();

			// return services.BuildServiceProvider(); // no castle windsor -> the demo works
			return services.AddWindsor(container, opts =>
			{
				opts.RegisterControllers(Component.For<HomeController>().LifestyleTransient());
			});
		}
	
		public void Configure(IApplicationBuilder app, IHostingEnvironment env)
		{
			app.UseDeveloperExceptionPage().UseMvc();
		}

	}
	
	public interface IMyDependency { }

	public class HomeController : ControllerBase
	{
		public HomeController(IEnumerable<IMyDependency> myDependencies)
		{ }

		[HttpGet("")]
		public string Get() => "Success";
	}
}

```

**Comment by jonorossi** [comment]
Where is this example project with a `HomeController` with an `IEnumerable<T>` dependency?

The ASP.NET Core Facility documentation doesn't even declare the `HomeController` class it uses:
https://github.com/castleproject/Windsor/blob/master/docs/aspnetcore-facility.md

Castle Windsor's docs have separate info on using collections of components as dependencies:
- https://github.com/castleproject/Windsor/blob/master/docs/resolvers.md
- https://github.com/castleproject/Windsor/blob/master/docs/faq.md#why-is-windsor-not-able-to-inject-array-or-list-of-components

**Comment by jirikanda** [comment]
> Where is this example project with a `HomeController` with an `IEnumerable<T>` dependency?
```c-sharp
public HomeController(IEnumerable<IMyDependency> myDependencies)
```

Extending embedded ASP.NET Core Service Provider should **extend** DI container posibilities and **not limit** the posibilities. There is no issue with Castle Windsor resolvers, just the boilerplate should add CollectionResolver to be compatible with the ASP.NET Core Service Provider. Therefore I suggest to add the CollectionResolver to the example (https://github.com/castleproject/Windsor/blob/master/docs/aspnetcore-facility.md#what-do-i-need-to-set-it-up).

**Comment by jonorossi** [comment]
Windsor is never going to be completely compatible with the built-in container, it isn't the built-in container, however feel free to submit a pull request to update the docs.
