### ISSUE TITLE
New Feature - WebObjectActivator support for ASP.NET Web Forms

### ISSUE THREAD

**Issue by alexmbaker** [castleproject/Windsor#479]
.NET Framework 4.7.2 brings dependency injection to legacy web forms through [HttpRuntime.WebOjectActivator](https://docs.microsoft.com/en-us/dotnet/api/system.web.httpruntime.webobjectactivator?view=netframework-4.7.2
).  I have found a few Castle Windsor based implementations using the Google machine however I don't think they are really using the container correctly.

Including a Castle Project endorsed implementation in the Castle.Facilities.AspNet.SystemWeb package would be:

- Great for developers who need to support older APS.NET Web Forms applications who wish to bring modern development practices to their work
- Great for the Castle Project as it makes adoption simple and quick
- Great for the Castle Project as it discourages incorrect usage of the container

**Comment by jirikanda** [comment]
See our implementation at https://github.com/havit/Havit.CastleWindsor.WebForms.
If you have any questions do not hesitate to open an issue with your question there.

**Comment by jonorossi** [comment]
Thanks @jirikanda, sounds like there is a solution. Unless someone contributes an implementation to Windsor this isn't going to happen, closing.
