### ISSUE TITLE
Windsor 5: Idea to deal with PerWebRequest scope in XML

### ISSUE THREAD

**Issue by thuannguy** [castleproject/Windsor#482]
I have an enterprise application that makes use of both XML registration and programmatically convention-based registration. Moving away from XML is not an option. Most component registrations I have in XML use PerWebRequest. Thus, Windsor 5.0 throwed the following error:

```CSharp
[ArgumentException: Requested value 'PerWebRequest' was not found.]
   System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult) +1078
   System.Enum.Parse(Type enumType, String value, Boolean ignoreCase) +109
   Castle.MicroKernel.SubSystems.Conversion.EnumConverter.PerformConversion(String value, Type targetType) +44

[ConverterException: Could not convert from 'PerWebRequest' to Castle.Core.LifestyleType.]
   Castle.MicroKernel.SubSystems.Conversion.EnumConverter.PerformConversion(String value, Type targetType) +201
   Castle.MicroKernel.SubSystems.Conversion.DefaultConversionManager.PerformConversion(String value, Type targetType) +195
   Castle.MicroKernel.SubSystems.Conversion.DefaultConversionManager.PerformConversion(String value) +41
   Castle.MicroKernel.ModelBuilder.Inspectors.LifestyleModelInspector.ReadLifestyleFromConfiguration(ComponentModel model) +140
   Castle.MicroKernel.ModelBuilder.Inspectors.LifestyleModelInspector.ProcessModel(IKernel kernel, ComponentModel model) +28
   System.Collections.Generic.List`1.ForEach(Action`1 action) +101
   Castle.MicroKernel.ModelBuilder.DefaultComponentModelBuilder.BuildModel(IComponentModelDescriptor[] customContributors) +208
   Castle.MicroKernel.Registration.ComponentRegistration`1.Castle.MicroKernel.Registration.IRegistration.Register(IKernelInternal kernel) +121
   Castle.MicroKernel.DefaultKernel.Register(IRegistration[] registrations) +72
   Castle.Windsor.WindsorContainer.Register(IRegistration[] registrations) +49
   Castle.Windsor.Installer.DefaultComponentInstaller.SetUpComponents(IConfiguration[] configurations, IWindsorContainer container, IConversionManager converter) +692
   Castle.Windsor.Installer.DefaultComponentInstaller.SetUp(IWindsorContainer container, IConfigurationStore store) +222
   Castle.Windsor.WindsorContainer.Install(IWindsorInstaller[] installers, DefaultComponentInstaller scope) +152
   Castle.Windsor.WindsorContainer.Install(IWindsorInstaller[] installers) +137
```

Could anyone please suggest a way to deal with this issue? Thanks for reading 😄

**Comment by jonorossi** [comment]
Changing from the now removed "per web request" lifestyle type to the scoped lifestyle with a scope accessor over `System.Web` would look like this. Appears the docs for XML configuration haven't been updated:

```xml
<configuration>
  <components>
    <component
      service="..."
      type="..."
      lifestyle="scoped"
      scopeAccessorType="Castle.Facilities.AspNet.SystemWeb.WebRequestScopeAccessor, Castle.Facilities.AspNet.SystemWeb">
    </component>
  </components>
</configuration>
```

Not sure if you can use a property, e.g. `scopeAccessorType="${webScopeAccessorType}"`.

These need some updating:
- https://github.com/castleproject/Windsor/blob/master/docs/xml-registration-reference.md
- https://github.com/castleproject/Windsor/blob/master/docs/registering-components.md
- https://github.com/castleproject/Windsor/blob/master/docs/systemweb-facility.md

**Comment by thuannguy** [comment]
@jonorossi Thank you. It works like a charm. Here is a small PR to update guideline: https://github.com/castleproject/Windsor/pull/483. My first ever so not sure if it is done the right way though 😄

**Comment by jonorossi** [comment]
@thuannguy thanks, I've merged #483 and made some changes in 02516c5efa07a1e3822d6ba0058f8bcce5856f11. I moved the added section to the System Web facility page so it is all kept together and a few other small changes. Congrats on your first pull request :tada:.

**Comment by thuannguy** [comment]
@jonorossi  thank you. Even though it needed a lot of edit, I would consider it a good start 😄

**Comment by jonorossi** [comment]
@thuannguy definitely a good start. Nothing would have made its way into the docs without you.
