### ISSUE TITLE
Asp.NET Core Facility and Filters

### ISSUE THREAD

**Issue by drewtownchi** [castleproject/Windsor#485]
Filters were working when we were using the `Castle.Windsor.MsDependencyInjection` reference but since switching to `Castle.Facilities.AspNetCore` we are having a difficult time.  It seems like we should be using the `CrossWired()` extension method based on the documentation. But, due to our heavy use of Installers this is impractical.

Example

```c#
        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            Container = new WindsorContainer();
            Container.AddFacility<AspNetCoreFacility>(f => f.CrossWiresInto(services));
            
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
            services.AddScoped<TrackingFilter>();

            Container.Install(new ConfigurationInstaller());
            return services.AddWindsor(Container);
        }
```

Results in a ` Unable to resolve service for type 'blah.blah.IProvideConfiguration' while attempting to activate 'blah.blah.TrackingFilter'.`

Am I missing something?  Is there an easier way to allow Asp.net filters to resolve Windsor injected dependencies?

**Comment by dariuslf** [comment]
You have to explicitly use `CrossWired()` for those components you want the framework to be able to resolve.

**Comment by jonorossi** [comment]
Closing as @dariuslf provided an answer. `Castle.Windsor.Extensions.DependencyInjection` is also the path forward for ASP.NET Core 3.x.
