### ISSUE TITLE
Remove the dependency on ASPNET Core  in Asp.NET Core Facility, just use .NET Core

### ISSUE THREAD

**Issue by schwarzie2478** [castleproject/Windsor#487]
I took some initiative to add the facility to the list of supported third party containers in the repository https://github.com/aspnet/Extensions while I was investigating how to use it for my own work.

I got a question from david fowler about the current implementation.   
I'm not really the guy to answer him,  so I leave this here to let you guys  decide.

Can the code be changed to not depend on  asp.net core and only on the .NET core dependency injection infrastructure?

Pull request with the change if somebody is interested: [https://github.com/aspnet/Extensions/pull/1632](https://github.com/aspnet/Extensions/pull/1632)

**Comment by jonorossi** [comment]
There is no active maintainer for this facility, there unfortunately is no "you guys".

Your pull request obviously makes breaking changes, if you want to see this go in there needs to be a plan for this facility. It sounds like the facility won't work with ASP.NET Core 3.0 (#493), if the replacement facility is a `Microsoft.Extensions.DependencyInjection` integration then how that integration will work should be described.

**Comment by jonorossi** [comment]
Closing as `Castle.Windsor.Extensions.DependencyInjection` is the path forward for ASP.NET Core 3.x.
