### ISSUE TITLE
Use IPotentiallyMisconfiguredComponentsDiagnostic together with TypedFactoryFacility

### ISSUE THREAD

**Issue by Buthrakaur** [castleproject/Windsor#49]
I started to use TypedFactoryFacility, but I got immediately false positive IPotentiallyMisconfiguredComponentsDiagnostic-powered failing test. Is there any simple method how to instruct PotentiallyMisconfiguredComponentsDiagnostic to handle TypedFactoryFacility-provided components properly? I could filter handlers resulting from PotentiallyMisconfiguredComponentsDiagnostic to skip components waiting for services provided by TypedFactoryFacility, but this sounds quite demanding.

**Comment by fir3pho3nixx** [comment]
Closing this, it is potentially linked to https://github.com/castleproject/Windsor/issues/328. If you feel this is incorrect, please re-open this issue.
