### ISSUE TITLE
Broken link in ioc.md

### ISSUE THREAD

**Issue by chmolinari** [castleproject/Windsor#496]
The link on the bottom of the file docs/ioc.md, regardin a blog post by Stefano Mazzocchi, is broken.

Here's the link as it appears on the page: http://www.betaversion.org/~stefano/linotype/news/38/

**Comment by jonorossi** [comment]
Thanks @chmolinari. I've updated the docs: dc961ee5b44976c94e25eced9c0030cade870e11.

**Comment by chmolinari** [comment]
Thanks to you!
