### ISSUE TITLE
Could not load file or assembly Castle.Core, Version=4.1.1.0

### ISSUE THREAD

**Issue by TongZhai** [castleproject/Windsor#500]
I have this project (target .Net Framework 4.6) that uses Castle.Core (4.4.0) and Castle.Windsor (5.0.0), the nuget packages are there and references are good and it compile without error. But when runs, it failed here:

`WindsorContainer _container = new WindsorContainer()`

The error message:

`System.IO.FileNotFoundException: 'Could not load file or assembly 'Castle.Core, Version=4.1.1.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc' or one of its dependencies. The system cannot find the file specified.'`

I checked that I also have Moq.4.11.0 in the packages. I've also installed .net core 1.0 SDK that supports .netstandard 1.3 and 1.5. I've also updated the app.config file as below:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Castle.Core" publicKeyToken="407dd0808d44fbdc" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.4.0.0" newVersion="4.4.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
<startup><supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6" /></startup></configuration>
```

But it still fails that same place. I don't even know why it is asking for 4.1.1 in the first place because I don't have that version in the packages.

**Comment by jonorossi** [comment]
Pre-4.0 of Castle Core had an assembly version of `major.0.0.0`, then with the change to .NET CLI tooling in 4.0 we lost that set up until we fixed it again in 4.2.0 (2017-09-28), so it is again `major.0.0.0`.

Your assembly binding would then be wrong since that isn't the assembly version, I'd start by removing it, if the problem still persists then take a look at each assembly version and references to find the assembly that is trying to load 4.1.1.

**Comment by TongZhai** [comment]
@jonorossi are you referring to the possibility of me having multiple previous versions of Castle.Core/Windsor on my computer? if yes, then I might add that this is a brand new computer that I just had it for couple of weeks, so there is not previous version of anything, it just starts with the Castle 4.4.0 version. Also, are you suggesting that there might be other libraries that might be referencing to that 4.1.1 version and try to correct them?

**Comment by TongZhai** [comment]
@jonorossi Ok, I got to say I don't really know what you mean: "Your assembly binding would then be wrong since that isn't the assembly version"? could you please elaborate a bit, given the information I described above?

**Comment by jonorossi** [comment]
> are you referring to the possibility of me having multiple previous versions of Castle.Core/Windsor on my computer?

No.

> are you suggesting that there might be other libraries that might be referencing to that 4.1.1 version and try to correct them?

Yes. If the `Castle.Windsor` 5.0.0 assembly and `Moq` 4.11.0 assembly are referencing `Castle.Core` 4.0.0.0 (they are, just checked) then they aren't the ones causing the problem.

> Ok, I got to say I don't really know what you mean: "Your assembly binding would then be wrong since that isn't the assembly version"? could you please elaborate a bit, given the information I described above?

As I said above the `Castle.Core` assembly version is `major.0.0.0` (so Castle Core 4.4.0 has an assembly version of `4.0.0.0`), so specifying `newVersion="4.4.0.0"` is asking for an assembly that doesn't exist. I'd start by fixing your assembly binding policy.

**Comment by TongZhai** [comment]
@jonorossi are you suggesting below:

`<bindingRedirect oldVersion="0.0.0.0-4.4.0.0" newVersion="4.0.0.0" />`

**Comment by jonorossi** [comment]
> `<bindingRedirect oldVersion="0.0.0.0-4.4.0.0" newVersion="4.0.0.0" />`

We use the `major.0.0.0` assembly version format so users don't need binding redirects, we do making breaking public API changes between major versions.
