### ISSUE TITLE
Can I override castle resolution(resolve) behavior?

### ISSUE THREAD

**Issue by mdora5251** [castleproject/Windsor#502]
I have asked before on stackoverflow, this is very important for me, thank you for your help

Probably, my question is very simple but i was really stuck in this section. I want to override behavior of castle windsor resolve function and i looked to related answers on this site but not helpful to me.

Actualy if you want to hear the real problem i want to understand castle resolve function lifecycle. As well as I know when I add subresolver to kernel module Castle always use default resolver and the default resolver is what i dont want to thing.

Shortly, i'll explain with code.

This is the my bootstrapper function it's add the ResolverByNameConvention into subresolver list.

`
   public static ContainerBootstrapper Bootstrap(IResource resource)
    {
        var container = new WindsorContainer();

        container.Kernel.Resolver.AddSubResolver(new ResolverByNameConvention(container));
        container.Install(Configuration.FromXml(resource));

        return new ContainerBootstrapper(container);
    }`

And this is the what i use(at least similar like that)

` 
   public class ResolverByNameConvention :  ISubDependencyResolver
   {
    private readonly IWindsorContainer Container;

    public ResolverByNameConvention(IWindsorContainer container)
    {
        Container = container;
    }

    public bool CanResolve(CreationContext context, ISubDependencyResolver contextHandlerResolver, ComponentModel model, DependencyModel dependency)
    {
        return true;
    }

    public object Resolve(CreationContext context, ISubDependencyResolver contextHandlerResolver, ComponentModel model, DependencyModel dependency)
    {

        return Container.Resolve<ITools>(componentId);
    }
   } `

Actually i expect the default resolve function does resolve through subresolver but it(castle) resolve default resolver

At last, usage is like that;

` ISystemXslResolver xslResolver = Container.Windsor.Container.Instance.Kernel.Resolve<ISystemXslResolver>();`

If needed to repeat it, when i use the xslResolver i expect xslResolver is ResolverByNameConvention.Resolve function to be

**Comment by dquist** [comment]
When creating the container you can pass in a custom `IDependencyResolver` to the kernel which will prevent the default resolver from being used.

Define your custom resolver class

```c#
public class CustomDependencyResolver : IDependencyResolver
{
    // ...
}
```

Then create the container, specifying your custom resolver in the MicroKernel constructor.

```c#
var container = new WindsorContainer(
    new DefaultKernel(
        new CustomDependencyResolver(),
        new NotSupportedProxyFactory()),
    new DefaultComponentInstaller());
```

IMO there should be a better API for replacing the built-in resolver, but this should work.

**Comment by mdora5251** [comment]
thank you so much @dquist i'll try it to implement and i hope will help me. if so, i'll write here
