### ISSUE TITLE
Nancy.Hosting.Self.NancyHost -> WebRequestScopeAccessor. Castle 5.0.x

### ISSUE THREAD

**Issue by generik0** [castleproject/Windsor#511]
Hi

The [Nancy.Bootstrappers.Windsor](https://github.com/NancyFx/Nancy.Bootstrappers.Windsor) with nancy self hosted is throwing a
`Could not load type 'Castle.MicroKernel.Lifestyle.WebRequestScopeAccessor' from assembly 'Castle.Windsor, Version=5.0.0.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc'.
`
exception. Works with Castle <=4.1

Any thoughts? Thanks!

**Comment by jonorossi** [comment]
- https://github.com/castleproject/Windsor/blob/master/CHANGELOG.md#500-beta001-2018-10-26
- https://github.com/castleproject/Windsor/blob/master/docs/systemweb-facility.md

**Comment by generik0** [comment]
Thanks @jonorossi 
Yes I see now it is moved over the Castle.Facilities.AspNet.SystemWeb facility. 
And you can not just plugin System.Web anymopre.

Not good for Nancy.Hosting.Self.NancyHost :-(

But i can add manually to my own lib. Thanks, mate,...
