### ISSUE TITLE
Wrong namespace in Windsor/blob/master/docs/systemweb-facility.md

### ISSUE THREAD

**Issue by Demiurg-ls** [castleproject/Windsor#513]
Hi,
It seems there is a wrong 

Castle.Facilities.AspNet.SystemWeb.Lifestyle

namespace of **PerWebRequestLifestyleModule** specified instead of:

Castle.Facilities.AspNet.SystemWeb

**Comment by jonorossi** [comment]
Thanks, yep that is wrong. I've fixed the docs in 4830718f99fd71e539133b34f9e54daa49049d6f.
