### ISSUE TITLE
Windsor does not build due to projecticonurl being obsolete

### ISSUE THREAD

**Issue by generik0** [castleproject/Windsor#518]
Hi @jonorossi 

Unfortunately in master Windsor does not build. MS have made the csproj projecticonurl become a warning. and the Windsor does not build with warnings.

MS recommend using the the csproj projecticon attribute. But this requires either:
1. The icon is downloaded at build time and referenced with path, or
2. The Windsor icon is added to the repo and references with path

We can also:

3. add NU5048  to the no warn for the the build

I personally think option 2 is best. Anyone else have any thoughts or experiences?

**Comment by jonorossi** [comment]
> Unfortunately in master Windsor does not build

Not sure what on AppVeyor hasn't been updated to the newest version, because I just rebuilt master (build 659) and it was successful.

We've already got the 128x128 logo in the repository at `docs/images/windsor-logo.png`, so no need to copy it from the web site repo.

It appears that `PackageIconUrl` was marked with an obsolete warning late last year, and that the embedded icon support was added to [NuGet 5.3](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-5.3). If we remove the URL then anyone using an older NuGet client will loose the icon, but that probably isn't a big problem. Suppressing the warning is the quickest option, but it would be good to get the icon and license embedded.

@stakx whatever decision we make here we should do the same in Castle Core, what do you think?

**Comment by jonorossi** [comment]
@generik0 fork and pull request is the easiest way, we rarely use feature branches, Extensions.DependencyInjection is an exception because so many people are working on the one feature and it needs to work for everyone before it is worth merging.

@generik0 did you have a chance to follow up on my previous comment about support for embedded icons in NuGet clients so we know which option we are going with?

**Comment by generik0** [comment]
@jonorossi no probs. i will do a fork and a pr ti master.
I didn't pickup on your comment/question about the pre nuget 5.3 clients. 
I can tell you that the changes I just did on my "day jb" today, I checked with an old "NuGet Package Explorer" the icons were not showing here. After I updated, they were showing.
It was just showing a broken icon, as there was no projecticonurl filled out anymore.

So you are right, old nuget <5.3 will not show an icon. Hence it is up to you guys what you want.. No icon of old nuget clients. 

A funny thing though. The with nugets in Azure DevOps Attributes the "old" projectIconUrl is browsing with icon, however, not for projecticon when using VS2019 latest, and nuget browse....

Upon installation, the icon is ok...
![image](https://user-images.githubusercontent.com/2411563/80723797-5d9cb280-8b01-11ea-8f85-33a71d68c1ff.png)

Thinks we would need to test the nuget with a prerelease for castle. The Azure Devops Artifacts do behave a little funny sometimes...

**Comment by jonorossi** [comment]
> So you are right, old nuget <5.3 will not show an icon. Hence it is up to you guys what you want.. No icon of old nuget clients.

Yer, let's move forward and only embed it, the majority of clients are using 5.3+ (according to https://www.nuget.org/stats). A missing icon in old clients doesn't break anything, they'll just get the default NuGet logo icon.

I just checked JSON.NET and it only has an embedded icon, no URL:

https://github.com/JamesNK/Newtonsoft.Json/blob/666d9760719e5ec5b2a50046f7dbd6a1267c01c6/Src/Newtonsoft.Json/Newtonsoft.Json.csproj#L21-L22

**Comment by generik0** [comment]
> I just checked JSON.NET and it only has an embedded icon, no URL:

Interestingly they have also PackageIconFullPath element
and include the full path.. Bit different than MS recommendation. I will try this tomorrow and see if it helps my package browse icon :-)

<None Include="$(PackageIconFullPath)" Pack="true" PackagePath="\"/>

I'll look at it tomorrow :-)

**Comment by stakx** [comment]
I've run a few quick experiments.

 * NuGet won't complain when we have both a `<PackageIconUrl>` and a `<PackageIcon>`.
 * Omitting `<PackageIconUrl>` will break NuGet package icons in VS2017's Nuget Package Manager.
* When including both properties, the package icon is displayed in both VS2017's and VS2019's Nuget Package Manager.

Based on those three facts, I'm coming to the conclusion that we should include both properties.

(Disclaimer: I don't know what `<PackageIconFullPath>` is about, and I haven't tried it.)

**Comment by generik0** [comment]
Good idea....
Only issue is the build Warming causing the build to fail. Add to props = ok?

**Comment by stakx** [comment]
>  Only issue is the build Warming causing the build to fail. Add to props = ok?

The build warning should disappear once you add a `<PackageIcon>`.

These are the changes I suggest:

```diff
diff --git a/buildscripts/common.props b/buildscripts/common.props
index fcf635bf7..e9200900a 100644
--- a/buildscripts/common.props
+++ b/buildscripts/common.props
@@ -20,6 +20,7 @@
                <AssemblyVersion>$(BuildVersionMajor).0.0</AssemblyVersion>
                <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
                <PackageProjectUrl>http://www.castleproject.org/</PackageProjectUrl>
+               <PackageIcon>castle-logo.png</PackageIcon>
                <PackageIconUrl>http://www.castleproject.org/img/castle-logo.png</PackageIconUrl>
                <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
                <PackageVersion>$(BuildVersion)</PackageVersion>
@@ -33,6 +34,7 @@
        <ItemGroup>
                <Content Include="..\..\CHANGELOG.md" />
                <Content Include="..\..\LICENSE" Pack="True" PackagePath="" />
+               <Content Include="..\..\docs\images\castle-logo.png" Pack="True" PackagePath="" />
                <Content Include="..\..\buildscripts\ASL - Apache Software Foundation License.txt" />
                <Content Include="..\..\buildscripts\readme.txt" />
        </ItemGroup>
```

I cannot find any documentation on the 'net, nor any mention of `<PackageIconFullPath>` inside VS2017/19's MSBuild files, so for now I am assuming that this property is essentially meaningless.
