### ISSUE TITLE
Windsor Optional Constructor Parameters is not working for integer type

### ISSUE THREAD

**Issue by karthi5589** [castleproject/Windsor#525]
The below code always resolving integer default value as 0 not -7.

    var container = new WindsorContainer();
    container.Register(Component.For<TestClass>());
    container.Resolve<TestClass>(); //boom

-----------------------------------------------------------

    public class TestClass
    {
        public TestClass(int test=-7)
        {
          //always 0 not -7.
        }
    }

**Comment by jonorossi** [comment]
Could you debug Windsor's `DefaultDependencyResolver` class to determine where things are going wrong:

https://github.com/castleproject/Windsor/blob/603d78d491790c88cff604051c92115e8bb5d9f9/src/Castle.Windsor/MicroKernel/Resolvers/DefaultDependencyResolver.cs#L137-L142

We've got some unit tests in `DefaultValueTestCase` but it is missing one for a value type which isn't registered.

**Comment by karthi5589** [comment]
@jonorossi - Thanks much. 
Perfect and it is working now :-)
