### ISSUE TITLE
Extensions.DependencyInjection: Add extension to use LifeStyle.ScopedToNetServiceScope on BasedOnDescriptor

### ISSUE THREAD

**Issue by MishaD87** [castleproject/Windsor#531]
Hi,
I was using Windsor together with MS DI inside Blazor. Now I can finally use Windsor entirely, thanks for developed extension.
I am in a process of migration of some services registrations from MS DI -> Windsor. Some of them have to be scoped.
In documentation I found a way how to do it (using LifeStyle.ScopedToNetServiceScope), but this works per component. 
I was using such construction before to register all my singleton/transient services. It would be perfect if there would be a way how to do it also for "MS DI Scoped" services. For example some extension method on BasedOnDescriptor (like LifeStyle.ScopedToNetServiceScope) or make ExtensionContainerScopeAccessor public.

![image](https://user-images.githubusercontent.com/36815881/85131664-e69db380-b23f-11ea-8d2f-3949ea58f919.png)

**Comment by ltines** [comment]
@MishaD87 Should be fairly easy to do. In meantime you can do
```
...
.WithServiceSelf()
.Configure(reg => reg.LifeStyle.ScopedToNetServiceScope())
...
```


@jonorossi what target branch you want the PR?

**Comment by jonorossi** [comment]
@ltines master

**Comment by generik0** [comment]
@MishaD87 We have merge an update for the DependencyInjection. I think it will be in NuGet soon. This allows you to extend the DependencyInjection implementation, (overriding methods) and also get control of the container.
Does this help your issue?

**Comment by generik0** [comment]
@ltines @MishaD87 is this still an issue, or should the 
`.WithServiceSelf()
.Configure(reg => reg.LifeStyle.ScopedToNetServiceScope())`
just be documented?

**Comment by jonorossi** [comment]
Pull request merged.
