### ISSUE TITLE
Support for ASP.NET Core 3.x  WebHost

### ISSUE THREAD

**Issue by generik0** [castleproject/Windsor#534]
Hi @jonorossi and @ltines 
Should the new ms dependency injection support WebHost / WebHost?

I know it is "Web Host, which remains available only for backward compatibility"

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-3.1

![image](https://user-images.githubusercontent.com/2411563/86609866-d5c59f80-bfac-11ea-89f6-7b2fe0c404cb.png)

**Comment by generik0** [comment]
Looks like IWebHostBuilder  / IwebHost is in Microsoft.AspNetCore.Hosting, not Microsoft.Extensions.Hosting, maybe the best plan is not to integrate ofr now!??

**Comment by AntonioDrusin** [comment]
This is probably a bit of work for people converting from 2.2. But I agree with @generik0 that for now it's best to just support 3.x best practices for now.
