### ISSUE TITLE
NetCore 3.x getting Container at ConfigureServices 

### ISSUE THREAD

**Issue by generik0** [castleproject/Windsor#535]
Hi @ltines 

in the help [net-dependency-extension](https://github.com/castleproject/Windsor/blob/master/docs/net-dependency-extension.md) it states:
"Alternatively you can create ConfigureServices method in Startup class that gets passed the IWindsorContainer"
What do you mean by this. If i:

```c#
public void ConfigureServices(IServiceCollection services, IWindsorContainer container)
        {
            services.AddControllers();
        }
```
I get an exception: "The ConfigureServices method must either be parameterless or take only one parameter of type IServiceCollection."

And the "ConfigureContainer" is called after "ConfigureServices"

Is there any way we can control the container? I.e. so e.g. we pass the container into UseWindsorContainerServiceProvider(),
e.g.:

```c#
            Host.CreateDefaultBuilder(args).UseWindsorContainerServiceProvider(contariner)
```

**Comment by generik0** [comment]
@jonorossi @ltines I think the ServiceCollectionExtensions is not needed. The logic should be contained in the factory with small method calls and virtuals. I..e SO**L**ID, ie. substitution principle.
The extension is not expandable. A factory would be...
Thoughts? Put CreateContainer into WindsorServiceProviderFactory with nice small methods?

**Comment by generik0** [comment]
Hi again everyone

I have noticed that instead of the UseWindsorContainerServiceProvider is is possible to add the startup base on the Startup with a factory implementation.
This might be good to add to md?

Also, gives even more reason to allow substitution of the factory and methods, instead of an extension?

```c3
public class Startup: StartupBase<IWindsorContainer>
    {
        public Startup(IConfiguration configuration) : base(new WindsorServiceProviderFactory())
        {
            Configuration = configuration;
        }
```

**Comment by generik0** [comment]
@ltines 
I have noticed that the CreateBuilder/ ServiceCollectionExtensions CreateContainer cleans the container of any registrations i have made at the:
```c#
container.Kernel.AddSubSystem(
				SubSystemConstants.NamingKey,
				new SubSystems.DependencyInjectionNamingSubsystem()
			);
```

Any thoughts how to stop this?

**Comment by ltines** [comment]
> 
> 
> Hi @ltines
> 
> in the help [net-dependency-extension](https://github.com/castleproject/Windsor/blob/master/docs/net-dependency-extension.md) it states:
> "Alternatively you can create ConfigureServices method in Startup class that gets passed the IWindsorContainer"
> What do you mean by this. If i:
> 
> ```cs
> public void ConfigureServices(IServiceCollection services, IWindsorContainer container)
>         {
>             services.AddControllers();
>         }
> ```
> 
> I get an exception: "The ConfigureServices method must either be parameterless or take only one parameter of type IServiceCollection."
> 
> And the "ConfigureContainer" is called after "ConfigureServices"
> 
> Is there any way we can control the container? I.e. so e.g. we pass the container into UseWindsorContainerServiceProvider(),
> e.g.:
> 
> ```cs
>             Host.CreateDefaultBuilder(args).UseWindsorContainerServiceProvider(contariner)
> ```
@generik0 
That's a typo - it should be `ConfigureContainer(IWindsorContainer container)`

**Comment by generik0** [comment]
> Hi again everyone
> 
> 
> 
> I have noticed that instead of the UseWindsorContainerServiceProvider is is possible to add the startup base on the Startup with a factory implementation.
> 
> This might be good to add to md?
> 
> 
> 
> Also, gives even more reason to allow substitution of the factory and methods, instead of an extension?
> 
> 
> 
> ```c3
> 
> public class Startup: StartupBase<IWindsorContainer>
> 
>     {
> 
>         public Startup(IConfiguration configuration) : base(new WindsorServiceProviderFactory())
> 
>         {
> 
>             Configuration = configuration;
> 
>         }
> 
> ```
Hi @ltines 
An update on this, when using the web integration for the host, this does not work. It apparently does not use IStartup for Startup, and it does not allow the factory to be ctor injected :-/

**Comment by generik0** [comment]
Hi @ltines, @robertmircea, @robsonj

Can anyone comment on this task and/or PR? 
I think this is important for 5.1 and to ensure openness of the facility :-)

**Comment by generik0** [comment]
PR is completed I will close issue when i have tested the nuget package and implementation and doco. Thanks @jonorossi
