### ISSUE TITLE
Castle.Windsor.Extensions.DependencyInjection Cleanup

### ISSUE THREAD

**Issue by generik0** [castleproject/Windsor#536]
Hi @jonorossi and @ltines.

I went through the Castle.Windsor.Extensions.DependencyInjection with a fine come and cleaned up.
Do you want the refactoring?
I will make a PR

**Comment by generik0** [comment]
Hi.
This branch is important because I found unused methods, fields. And in general some things needed cleaning up ;-)

**Comment by generik0** [comment]
@ltines i have noticed that https://github.com/castleproject/Windsor/blob/8a7d927a375a1d6d7836de0c44cec74c3219a6ec/src/Castle.Windsor.Extensions.DependencyInjection/Scope/ExtensionContainerRootScope.cs#L19
Has a static var used to keep the root scope?

Are we sure using static isn't anti-OO / not SOLID?
Could something else be used? Maybe get the logic out of an extension to a class instance?

**Comment by ltines** [comment]
@generik0 the root scope is there so singleton instances can be linked to a scope with explicit Dispose (.NET expects singletons to be disposed on dispose of "outermost" ServiceProvider

**Comment by generik0** [comment]
Hi @ltines 
Yes I understand that. I just think it might be a little anti IOC/ anti pattern exposing a internal static prop for a class.
I have tried to figure out an alternative, but cannot...

**Comment by generik0** [comment]
@jonorossi i will close this. The current implementation is good enough
