### ISSUE TITLE
Handle TypedFactoryFacility in IPotentialLifestyleMismatchesDiagnostic implementation

### ISSUE THREAD

**Issue by augi** [castleproject/Windsor#54]
`IPotentialLifestyleMismatchesDiagnostic` gets false-positive when component uses `TypedFactoryFacility`. @kkozmic mentioned in [this thread](https://github.com/castleproject/Windsor/issues/49) that it's possible to suppress this kind of warnings.

**Comment by fir3pho3nixx** [comment]
This is potentially linked to https://github.com/castleproject/Windsor/issues/328, closing for now. Please re-open if you feel this is a mistake. Resolution determinism is quite difficult given the extension points using the container.
