### ISSUE TITLE
Interceptor not support .net core 3.1?

### ISSUE THREAD

**Issue by tanghaojie** [castleproject/Windsor#541]
I'm use ASP.NET Boilerplate  build my application . .net core3.1 , castle core 4.4.
I had customed an interceptor like this [Creating Interceptors](https://aspnetboilerplate.com/Pages/Documents/Articles/Aspect-Oriented-Programming-using-Interceptors/index.html)
![image](https://user-images.githubusercontent.com/14171892/87131705-619a3d00-c2c7-11ea-9ef1-65c80beeace5.png)
debug shows Constructor Breakpoint be hitted, but `Intercept` method never be called. anything wrong?

**Comment by tanghaojie** [comment]
Test in .net framework 4.6.1, work fine
![image](https://user-images.githubusercontent.com/14171892/87136591-4a128280-c2ce-11ea-9340-83a2bac08314.png)

**Comment by ismcagdas** [comment]
@tanghaojie I'm one of the maintainers of AspNet Boilerplate and we are using interceptors in .NET Core 3.1. Could you create an issue on https://github.com/aspnetboilerplate/aspnetboilerplate so we can try to help you ?

**Comment by tanghaojie** [comment]
[Done](https://github.com/aspnetboilerplate/aspnetboilerplate/issues/5707)
