### ISSUE TITLE
Extensions.DependencyInjection: Existing services in container are cleared when registering in host

### ISSUE THREAD

**Issue by robertcoltheart** [castleproject/Windsor#550]
The use case is creating a container and registering components before registering it with the host. The naming sub-system is replaced, and all existing components are cleared.

The following example fails:

```c#
public interface IFileSystem
{
}

public class FileSystem : IFileSystem
{
}

public interface ICustomFileWriter
{
}

public class CustomFileWriter : ICustomFileWriter
{
	public CustomFileWriter(IFileSystem fileSystem)
	{
	}
}

public class Startup
{
	public void Configure(IApplicationBuilder app, ICustomFileWriter writer)
	{
            // ICustomFileWriter fails to resolve
	}
}

public class Program
{
	public static void Main(string[] args)
	{
		var container = new WindsorContainer();
		container.Register(Component.For<IFileSystem>().ImplementedBy<FileSystem>());

		Host
			.CreateDefaultBuilder()
                        // Register our own container
			.UseWindsorContainerServiceProvider(container)
			.ConfigureServices(x => x.AddSingleton<ICustomFileWriter, CustomFileWriter>())
			.ConfigureWebHostDefaults(x => x.UseStartup<Startup>())
			.Build()
			.Run();
	}
}
```

**Comment by generik0** [comment]
@robertcoltheart the changes I made to the WindsorServiceProviderFactory opened up for a base, and hence you can substitute.
In this base, you can override the AddSubSystemToContainer.

Would this not help you. I.e. you make your own WindsorServiceProviderFactory implementation. One could argue that resetting the container makes it "conforming".

![image](https://user-images.githubusercontent.com/2411563/95321591-8c326c80-089b-11eb-955c-ca04ed0b9c11.png)

**Comment by robertcoltheart** [comment]
Yes, there are definitely ways around this. My point is that if you are using the `IHostBuilder` extensions, namely `UseWindsorContainerServiceProvider(this IHostBuilder hostBuilder, IWindsorContainer container)`, then the implication is that you can use your ready-built container in the ASP.NET Host. 

What _actually_ happens, however, is that all your components are are wiped out because the naming subsystem is replaced. If there is a cleaner or better way to make this more obvious, or work around for this, I'm happy to submit another PR.

**Comment by generik0** [comment]
Hi @robertcoltheart 
Yes i know they get wiped. This is why I fought to get the container exposed.
So before there wasn't even a work around for it..

I like your change, if @jonorossi thinks it is good, it will also solve issues for me!

**Comment by generik0** [comment]
@robertcoltheart when i got the container exposed in the service provider factory this was the only workaround i could get implemented:
I think your fix might be better...


![image](https://user-images.githubusercontent.com/2411563/95331205-f0f4c380-08a9-11eb-9f2e-426af689706d.png)

**Comment by robertcoltheart** [comment]
I have a viable workaround, which is to create the container, and immediately create a `WindsorServiceProviderFactory`, which sets the naming subsystem. After that I can configure my container, and finally add it to the host builder. So I'm happy with this approach for now. Someone that may know the inner workings of Windsor better than me might be able to attempt to solve this without using a new naming subsystem.
