### ISSUE TITLE
Decorators does not work anymore (5.1.0-beta001)

### ISSUE THREAD

**Issue by twenzel** [castleproject/Windsor#552]
After upgrading from v4.x to 5.1-beta I found that the decorators does not work anymore.

**Exception:**
```
HandlerException: Can't create component 'WebApplication3UsingWindsor.DecoratedUserService' as it has dependencies to be satisfied.

'WebApplication3UsingWindsor.DecoratedUserService' is waiting for the following dependencies:
- Service 'WebApplication3UsingWindsor.IUserService' which points back to the component itself.
A dependency cannot be satisfied by the component itself, did you forget to register other components for this service?
```

Using: Castle.Windsor.Extensions.DependencyInjection (5.1.0-beta001)

In previous version this was working:
```Csharp
container.Register(Component.For<IUserService>().ImplementedBy<DecoratedUserService>());
...
container.Register(Component.For<IUserService>().ImplementedBy<UserService>());
```

Now only this is working:
```Csharp
container.Register(
			Component.For<IUserService>().ImplementedBy<DecoratedUserService>(),
			Component.For<IUserService>().ImplementedBy<UserService>()
			);
```

I don't want to re-write the whole register logic in my application and try to find all occurences.

Is this new behavior by design?

I've attached a simple repro project.
[WebApplication3UsingWindsor.zip](https://github.com/castleproject/Windsor/files/5329218/WebApplication3UsingWindsor.zip)

**Comment by twenzel** [comment]
I think the error comes from `Castle.Windsor.Extensions.DependencyInjection`.
Using `Castle.Windsor.MsDependencyInjection` with `Castle.Windsor` (5.1.0-beta001) works like a charm.

**Comment by generik0** [comment]
HI @ltines this seams to what is causing the issue;:

![image](https://user-images.githubusercontent.com/2411563/95330273-93ac4280-08a8-11eb-84e4-76682ccc7934.png)
I though @robertcoltheart PR #551 but it doesn't.

@ltines can you tell us the reason for the "AddSubSystem" in the facility? and also, can you tell us why this might be giving an issue?
Thanks :-)

**Comment by generik0** [comment]
@ltines this will fix the issue;
Any thought to improving?

![image](https://user-images.githubusercontent.com/2411563/95332682-0ec32800-08ac-11eb-9410-8f1ab51fa0cb.png)

**Comment by generik0** [comment]
@jonorossi @ltines @twenzel @AntonioDrusin @robertcoltheart Got it.. Anyone have time to comment / review?
#556

**Comment by twenzel** [comment]
@generik0 I can confirm #556 fixes the issue.

**Comment by ltines** [comment]
> 
> 
> HI @ltines this seams to what is causing the issue;:
> 
> ![image](https://user-images.githubusercontent.com/2411563/95330273-93ac4280-08a8-11eb-84e4-76682ccc7934.png)
> I though @robertcoltheart PR #551 but it doesn't.
> 
> @ltines can you tell us the reason for the "AddSubSystem" in the facility? and also, can you tell us why this might be giving an issue? I see tests fail in the WindsorScopedServiceProviderTests, is it because of some resolving differences between service provider and windsor?
> 
> Thanks :-)
> 
> UPDATE. I sespect the issue is in here. DependencyInjectionNamingSubsystem, will investigate more

the custom subsystem is becuase we need specific order of components for a service to match .NET semantics
