### ISSUE TITLE
Castle.Core target frameworks vs Castle.Windsor

### ISSUE THREAD

**Issue by generik0** [castleproject/Windsor#564]
Hi @jonorossi 

The Castle.Core target references are:
`<TargetFrameworks>net45;netstandard2.0;netstandard2.1</TargetFrameworks>`

Should we align Castle.Windsor against Castle.Core?

Even better:

`<TargetFrameworks>net45;netstandard2.0;net5.0</TargetFrameworks>`

?

**Comment by generik0** [comment]
After a bit of local testing. Net45 and netstandard1.6 does not build.


So the question is, should we add 2.1 to the build for

**Comment by jonorossi** [comment]
I think this one will need to wait a bit. Castle.Core target frameworks in master are newer than the last release, we've not yet got to release Castle.Core 5.0.

- 4.4.1: `net35;net40;net45;netstandard1.3;netstandard1.5`
- master: `net45;netstandard2.0;netstandard2.1`

Now that `net5.0` is out, we'll add that and probably drop ns2.1.

**Comment by generik0** [comment]
@jonorossi please review PR whne you have time. Castle.Windsor looks ready to update target frameworks

**Comment by lg2de** [comment]
> Now that `net5.0` is out, we'll add that and probably drop ns2.1.

netstandard2.1 is used if referenced from dotnetcoreapp3.1. If you remove ns2.1 and add net5.0 you will not support dotnetcore 3.1. But 3.1 is LTS, net5.0 is NOT LTS.

**Comment by jonorossi** [comment]
> If you remove ns2.1 and add net5.0 you will not support dotnetcore 3.1. But 3.1 is LTS, net5.0 is NOT LTS.

Windsor today targets `net45;netstandard1.6`, so "dropping" ns2.1 in my comment was from the proposed list which @generik0 posted (since it isn't implemented), which would leave the new proposed list `net45;netstandard2.0;net5.0`.

Anyway, these comments are old compared to the discussion on the pull request.
