### ISSUE TITLE
The assembly 'Castle.Windsor [...] is not registered for COM Interop

### ISSUE THREAD

**Issue by FrancescoBonizzi** [castleproject/Windsor#604]
Hi! I have a .NET library with `Register for COM interop`_attribute set to true, and `COM visibile` too in `csproj`. This library references Castle.Windsor 5.1.1 on .NET Framework 4.8, and when I build, I get this compiler error:

`The assembly 'Castle.Windsor, Version=5.0.0.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc' is not registered for COM Interop. Please register it with regasm.exe /tlb.`

I noticed that with other nuget libraries (for example Dapper 2.0.90) I don't have any problem to compile a dll registered for COM Interop. Is there something I'm missing? If I manually register the dll with regasm, it works, but I'm wondering why I have to do it manually!

Thanks a lot.

**Comment by jonorossi** [comment]
Looks like it was broken when Windsor was moved to the .NET SDK project format and so the assembly is defaulting to COM visible.

`CommonAssemblyInfo.cs` doesn't have `[assembly: ComVisible(false)]` like Castle Core. `ComVisible(false)` used to be set via the MSBuild build scripts before the move.
