### ISSUE TITLE
Make Castle.Windsor.Extensions.DependencyInjection depend on abstractions

### ISSUE THREAD

**Issue by ikkentim** [castleproject/Windsor#624]
`Castle.Windsor.Extensions.DependencyInjection` currently depends on the implementations of the hosting and logging extensions. It would be nice if it could depend on the abstractions instead.

```diff
- <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.1.3" />
- <PackageReference Include="Microsoft.Extensions.Logging" Version="3.1.3" />
+ <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="3.1.3" />
+ <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="3.1.3" />
```

**Comment by ikkentim** [comment]
I also don't see why it has a dependency for `Microsoft.Extensions.Logging` in the first place, it doesn't even use it.

**Comment by jonorossi** [comment]
I asked the same question when this was contributed by a previous contributor and was told it had to work that way. Gladly accept the change.

**Comment by ikkentim** [comment]
I've attached a pull request for this change.
