### ISSUE TITLE
Split hosting extensions from Castle.Windsor.Extensions.DependencyInjection into separate package

### ISSUE THREAD

**Issue by ikkentim** [castleproject/Windsor#625]
`Castle.Windsor.Extensions.DependencyInjection` contains a dependency to hosting related packages (`Microsoft.Extensions.Hosting`). You however don't always need hosting when using `Microsoft.Extensions.DependencyInjection.Abstractions`. It would be great if the hosting related functions could be split off into a `Castle.Windsor.Extensions.Hosting` package.

For example, I'm working on implementing Windsor for a front-end application which uses Microsofts DI abstractions. I'd prefer not to have hosting related dependencies in my front-end application.

#624 would reduce the pain, but the change suggested in this issue would be much better.

**Comment by jonorossi** [comment]
Do you know how much code uses the Hosting package? I always wondered if it was just a little bit of code that could be provided as an example.

**Comment by ikkentim** [comment]
As far as I can see only this code:
https://github.com/castleproject/Windsor/blob/master/src/Castle.Windsor.Extensions.DependencyInjection/Extensions/HostBuilderExtensions.cs

These are nice to have extension methods for easily configuring Windsor on a HostBuilder.

**Comment by jonorossi** [comment]
Looks like Autofac has a separate package for it. We'd keep it in the same repo here.

https://github.com/autofac/Autofac.Extensions.Hosting

**Comment by jonorossi** [comment]
v6.0 has not yet been released if you wanted to get the change in before it goes out.

**Comment by ikkentim** [comment]
I'll see if I can get create a PR for this next week

**Comment by ikkentim** [comment]
I've created a PR for this.

**Comment by jonorossi** [comment]
Thanks @ikkentim, sorry for the silence.
