### ISSUE TITLE
Constructor selection fails when using interception in one of the dependency graph

### ISSUE THREAD

**Issue by cervengoc** [castleproject/Windsor#629]
Hi, 

We'd like to ask for your help with the following issue.

- Given a top-level service class `TopLevelService` having 2 dependencies
  - Required `TopLevelServiceOptions`
  - Optional `IDependencyServiceIntercepted`, implemented using constructor overloading
- Given that `IDependencyServiceIntercepted` is intercepted using an interceptor
  - This is set up using a `IContributeComponentModelConstruction`
- Given that everything is properly registered
- When I resolve the `TopLevelService`...
- Then it should use the constructor with 2 parameters, passing the resolved intercepted dependency service

But, instead, the library chooses the constructor having only the single `TopLevelServiceOptions` parameter.

As far as I could debug, the issue is that during resolution, the handler for `IDependencyServiceIntercepted` is still in `WaitingDependencies` state. If I'm not using the interceptor, the handler is in the proper `Active` state, and the resolution works as expected.

I've attached a simple console app reproducint the issue. It throws a `NullReferenceException` when it should not.

[IssueWithConstructorOverloadAndInterception.zip](https://github.com/castleproject/Windsor/files/9675145/IssueWithConstructorOverloadAndInterception.zip)

Thank you very much in advance for your support.

**Comment by jonorossi** [comment]
A quick look at the code and I'd have thought it would work. The [`InterceptorInspector`](https://github.com/castleproject/Windsor/blob/master/src/Castle.Windsor/MicroKernel/ModelBuilder/Inspectors/InterceptorInspector.cs) which converts `InterceptorAttribute` attributes uses `IContributeComponentModelConstruction`.

Does it work if you change the `InterceptorReference` to use the component type? i.e.:

```csharp
model.Interceptors.Add(new InterceptorReference(typeof(TestInterceptor)));
```

I assume you're aware there is another extensibility point: `IModelInterceptorsSelector`.

**Comment by cervengoc** [comment]
Hi @jonorossi ,

Thank you for your quick reply. First of all, sorry for the quality of the sample project, I've just now noticed that it doesn't even build, some refactoring has failed and also it was cut out from a solution where central package management was used.

Using the concrete type in the interceptor reference solves the issue, thank you.
