### ISSUE TITLE
Extend 'Potential Lifestyle Mismatches' diagnostic to all lifestyles

### ISSUE THREAD

**Issue by kkozmic** [castleproject/Windsor#64]
Also I wonder if we should remove  singleton --> transient warning.

Quite often (more often than not) it actually is what you want.

Also not sure how to handle pooled... I never really use it myself. Open for discussion here.

**Comment by fir3pho3nixx** [comment]
I believe this should be maintained, it warns a consumer in a lovely way that your disposables are probably not being tracked for transients and being consumed by singletons. Good way of telling people that windsor will not dispose this for you. If you are OK with this, I would like to close this issue.

**Comment by fir3pho3nixx** [comment]
We have also learnt that resolution determinism is almost impossible given:  https://github.com/castleproject/Windsor/issues/328

Closing this for now and will ask for forgiveness later.
