### ISSUE TITLE
Missing package Castle.Windsor.Extensions.Hosting

### ISSUE THREAD

**Issue by lmorvan** [castleproject/Windsor#653]
This [document **.NET Core 3.0 Dependency injection extension**](https://github.com/castleproject/Windsor/blob/master/docs/net-dependency-extension.md) clearly says that we can install the package `Castle.Windsor.Extensions.Hosting`. However, this package does not exist in [nuget.org](https://www.nuget.org/packages?q=Castle.Windsor.Extensions.Hosting).

So either we should update this doc to explain how to connect Windsor Container and MsDependencyInjection, or provide that package.

**Comment by jonorossi** [comment]
You're looking at the docs in the master branch, see #628.
