### ISSUE TITLE
NuGet packages still using deprecated `licenseUrl` element

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Windsor#657]
> WARNING: The <licenseUrl> element is deprecated. Consider using the <license> element instead. Learn more: https://aka.ms/deprecateLicenseUrl.,Readme missing. Go to https://aka.ms/nuget-include-readme learn How to include a readme file within the package.

Could someone submit a pull request to resolve this. The build warning came before tooling supported the newer `license` element so we suppressed the warning (#481), that suppression can now be removed too.

**Comment by Toxantron** [comment]
I'll take a look, should only take a couple of minutes.

**Comment by jeme** [comment]
@Toxantron Seems that you got away from that again?

@jonorossi Added a PR for comments, not sure if it was such a fix you had in mind, the issue lacked some context for me.
