### ISSUE TITLE
Product support question

### ISSUE THREAD

**Issue by JimGolden** [castleproject/Windsor#671]
Is this repo still supported?

**Comment by jonorossi** [comment]
Windsor as an open source project has been supported by volunteers for 20 years, the level of support has varied throughout it's lifetime. At the moment, there is no one contributing what I'd refer to as a "maintainer". There isn't and hasn't been commercial support, even though contributors have often worked on the project during work time as it benefits their employer.

It's up to people to make the project what they want it to be.
