### ISSUE TITLE
Castle event wiring facility and dynamic parameters throw EventWiringException

### ISSUE THREAD

**Issue by pecanw** [castleproject/Windsor#78]
When trying to link an event with a handler using Castle.EventWiringFacility when the target service has a dynamic dependency, I get the EventWiringException with following description: Publisher tried to start subscriber 'xxx' that is waiting for a dependency.

I have traced the code down to the facility and I have found the assertion:

```C#
private static void AssertValidHandler(IHandler handler, string subscriberKey)
{
  if (handler == null)
	throw new EventWiringException("Publisher tried to start subscriber " + subscriberKey + " that was not found");
  if (handler.CurrentState == HandlerState.WaitingDependency)
	throw new EventWiringException("Publisher tried to start subscriber " + subscriberKey + " that is waiting for a dependency");
}
```

The problem is that the component with dynamic dependency is always in `HandlerState.WaitingDependency` state.

Is there a way how to tell the Castle that it should consider the dynamic dependency as Valid instead of WaitingDependency?

If not, I think that the state should be changed or may be the assertion in `EventWiringFacility.AssertValidHandler` could be skipped. If I skip the assertion in debugger, everything is working fine, i.e. the service gets resolved and the event gets fired and handled.

Using a factory method instead of dynamic parameter solves the issue but is not a convenient way how to fix the problem in my application.

Please find the code below to reproduce the behavior:

```C#
using System;
using Castle.Facilities.EventWiring;
using Castle.Facilities.Startable;
using Castle.MicroKernel.Registration;
using Castle.Windsor;

namespace SmallTests
{
	public interface IA
	{
		string DynDep { get; }
		void EventHandler(object sender, EventArgs args);
	}

	public class A : IA
	{
		private readonly string _dynDep;

		public A(string dynDep)
		{
			_dynDep = dynDep;
		}

		public string DynDep
		{
			get { return _dynDep; }
		}

		public void EventHandler(object sender, EventArgs args)
		{
			Console.WriteLine("Event Handled");
		}
	}

	public interface IB
	{
		event EventHandler MyEvent;
		void RaiseEvent();
	}


	public class B : IB
	{
		public event EventHandler MyEvent;

		public virtual void RaiseEvent()
		{
			var handler = MyEvent;
			if (handler != null) handler(this, EventArgs.Empty);
		}
	}

	public class CastleTest
	{
		public static void CastleDynamicDependency()
		{
			var c = new WindsorContainer();
			c.AddFacility<EventWiringFacility>();
			c.AddFacility<StartableFacility>(f => f.DeferredStart());

			c.Register(Component.For<IA>().ImplementedBy<A>()
				.DynamicParameters((kernel, parameters) => parameters["dynDep"] = DateTime.Now.ToShortTimeString())
				.Named("A"));

			//This works fine, but I cannot use it in my project
			//c.Register(Component.For<IA>()
			//    .UsingFactoryMethod(kernel => new A(DateTime.Now.ToShortTimeString()))
			//    .Named("A"));

			c.Register(Component.For<IB>().ImplementedBy<B>()
				.PublishEvent(x => x.MyEvent += null,
					y => y.To<IA>("A", s => s.EventHandler(null, null))));

			var r = c.Kernel.GetHandler("A");
			Console.WriteLine(r.CurrentState);

			var a = c.Resolve<IA>();
			Console.WriteLine(a.DynDep);

			var b = c.Resolve<IB>();
			b.RaiseEvent();

			Console.ReadLine();
		}
	}
}
```
I have also posted the question on [stackowerflow](http://stackoverflow.com/questions/28174256/castle-event-wiring-facility-and-dynamic-parameters-throw-eventwiringexception).

**Comment by kkozmic** [comment]
Hi @pecanw 

Event Wiring facility is no longer supported so I'd say it's quite unlikely this is going to be fixed unfortunately.

I know it's not ideal but I'd recommend migrating away from using EventWiringFacility if that's an option

**Comment by pecanw** [comment]
Can you point me to another (supported) way to wire-up events and handlers in Windsor Castle?

**Comment by ekennedy6334** [comment]
Hi @pecanw  -- were you able to find another method to wire events?

**Comment by pecanw** [comment]
We are using Castle.Facilities.EventWiring, Version=4.0.0.0, but we got rid of the dynamic dependencies.

**Comment by jonorossi** [comment]
The source code is still easily accessible, still Apache 2.0 licensed and isn't very big, so if you do want to continue using the facility it would be pretty trivial to copy the code into your own project. That way you could also make any needed changes.

https://github.com/castleproject-deprecated/Castle.Windsor.Facilities/tree/master/src/Castle.Facilities.EventWiring
