### ISSUE TITLE
Add per-object behavior configuration in WCF Facility fluent syntax

### ISSUE THREAD

**Issue by kappasims** [castleproject/Windsor#80]
While it's super convenient that the WCF facility automatically wires up every behavior to your objects registered in the container, sometimes I only want it to apply to specific endpoints/services. Right now the only way I've found how to do this is on the ApplyXXXBehavior event, go through and inspect the object and conditionally apply the behavior if it's the type I want, otherwise do nothing. 

It would be helpful if there was a way to add a specific behavior in the fluent API, like .UsingBehavior<IMyEndpointBehavior>()

An alternative would be to apply an exclusion to the object in question, such as .PreventBehavior(typeof(MyServiceBehavior), typeof(MyOtherServiceBehavior))

**Comment by kkozmic** [comment]
Hi @kappasims 

Would you like to create a PR and try implementing it?

**Comment by kappasims** [comment]
@kkozmic 

Sure, I can take a crack at it, but it may be a while.

**Comment by fir3pho3nixx** [comment]
No PR closing
