### ISSUE TITLE
Why not provide function just like "TryResolve<T>" and "TryResolveAll<T>" ?

### ISSUE THREAD

**Issue by Libra927** [castleproject/Windsor#83]
Why not provide function just like "TryResolve＜T＞" and "TryResolveAll＜T＞" ?
For example:
Boolean TryResolve＜T＞(out T instance);
Boolean TryResolve＜T＞(String name， out T instance);
and so on...

**Comment by kkozmic** [comment]
This is not the kind of functionality that is aligned with Windsor's intended usage.
