### ISSUE TITLE
Passing dependencies down the resolution chain is not always honored

### ISSUE THREAD

**Issue by ondrejpialek** [castleproject/Windsor#85]
I have the scenario bellow where I use a typed factory to provide me with instances of `DelegatingWorker`. The unit test passes as long as the `DelegatingWorker` has only one constructor taking the `IAction`. But once both are present, and even though the `name` param is provided in the registration, it throws an exception complaining it cannot resolve it's dependencies. Notice that the error message actually lacks any details about what is missing (suggesting that the `DependencyInspector` correctly does not find any dependency missing).

I apologize for the lengthy test, this is as concise as I managed to make it.

``` c#
using Castle.Facilities.TypedFactory;
using Castle.MicroKernel;
using Castle.MicroKernel.Context;
using Castle.MicroKernel.Registration;
using Castle.MicroKernel.Resolvers;
using Castle.MicroKernel.Resolvers.SpecializedResolvers;
using Castle.Windsor;
using Castle.Windsor.Installer;
using Castle.Windsor.Proxy;
using NUnit.Framework;
using System;
using System.Collections.Generic;
using System.Linq;

namespace TestLibrary
{
    public interface IWorker { }

    public class CompositeWorker : IWorker
    {
        public CompositeWorker(params IWorker[] items) { }
    }

    public class DelegatingWorker : IWorker
    {
        public DelegatingWorker(IAction consumer) : this(null, consumer) { }

        public DelegatingWorker(string name, IAction consumer) { }
    }

    public class WorkerSpawner
    {
        private readonly IDelegatingWorkerFactory _delegatingWorkerFactory;

        public WorkerSpawner(IDelegatingWorkerFactory delegatingWorkerFactory)
        {
            _delegatingWorkerFactory = delegatingWorkerFactory;
        }

        public IEnumerable<IWorker> SpawnWorkers()
        {
            yield return _delegatingWorkerFactory.CreateWorker(new EndpointAddress());
        }
    }

    public interface IDelegatingWorkerFactory
    {
        DelegatingWorker CreateWorker(IEndpointAddress endpoint);
    }

    public interface IEndpointAddress { }

    class EndpointAddress : IEndpointAddress { }

    public interface IAction { }

    public class ProcessingCoordinator : IAction
    {
        public ProcessingCoordinator(IEndpointAddress endpoint)
        {

        }
    }

    public class InlineDependencyPassingDependencyResolver : DefaultDependencyResolver
    {
        protected override CreationContext RebuildContextForParameter(CreationContext current, Type parameterType)
        {
            if (parameterType.ContainsGenericParameters)
            {
                return current;
            }

            return new CreationContext(parameterType, current, true);
        }
    }

    [TestFixture]
    public class Tests
    {
        [Test]
        public void Test()
        {
            var kernel = new DefaultKernel(
             new InlineDependencyPassingDependencyResolver(),
             new DefaultProxyFactory());

            var container = new WindsorContainer(kernel, new DefaultComponentInstaller());
            container.Kernel.Resolver.AddSubResolver(new CollectionResolver(container.Kernel));

            container.AddFacility<TypedFactoryFacility>();

            container.Register(
                Component.For<IWorker>()
                    .UsingFactoryMethod(k =>
                        new CompositeWorker(
                            k.Resolve<WorkerSpawner>().SpawnWorkers().ToArray()
                            ))
                    .LifestyleSingleton(),

                Component
                    .For<IDelegatingWorkerFactory>()
                    .AsFactory(),

                Component
                    .For<DelegatingWorker>()
                    .ImplementedBy<DelegatingWorker>()
                    .DependsOn(Dependency.OnValue("name", "aaa"))
                    .LifestyleTransient(),

                Component.For<IAction>()
                    .ImplementedBy<ProcessingCoordinator>()
                    .LifestyleTransient(),

                Component
                    .For<WorkerSpawner>()
                );

            Assert.DoesNotThrow(() => container.Resolve<IWorker>());
        }
    }
}

```

I understand that passing inline dependencies is not recommended but since Castle supports such functionality it should work :)

**Comment by kkozmic** [comment]
Hi @ondrejpialek 

I have a few questions, but before I get to them, let me start by saying this: If I understand what your code is trying to do, I think it should just work. I wouldn't exactly say _that passing inline dependencies is not recommended_. For what you're doing (using `DependsOn`) is a perfectly valid scenario.

Now, to my questions:
* What's the reason for `InlineDependencyPassingDependencyResolver`? Like I said, the scenario should be supported OOTB (that is via plan vanilla `new WindsorContainer()`.
* You say _Notice that the error message actually lacks any details about what is missing_. This is interesting, I though (from the top of my head) it would give you a helpful message.
* What happens if you only have the second constructor, with two parameters? I don't have a working Windows VM at the moment to try it out myself.

**Comment by ondrejpialek** [comment]
Hi Krzysztof,

thanks for looking into this :)

*Re point number 1:*

The critical piece is
``` c#
    public interface IDelegatingWorkerFactory
    {
        DelegatingWorker CreateWorker(IEndpointAddress endpoint);
    }
```
and
``` c#
    public class DelegatingWorker : IWorker
    {
        public DelegatingWorker(IAction consumer) : this(null, consumer) { }

        public DelegatingWorker(string name, IAction consumer) { }
    }
```

`IDelegatingWorkerFactory` spawns these workers, who require an `IAction` dependency. This dependency then in turn requires `IEndpointAddress`. This is where `InlineDependencyPassingDependencyResolver` comes into play. It passes the inline dependency provided to `IDelegatingWorkerFactory` all the way to `IAction` (there are more levels in our real app). This is what is discouraged - it surfaces a dependency or dependent components where these should be an implementation detail. This is not the main point of the bug report though.

*Re point number 2:*

I have left the company I've been with since this bug has been posted so I can only share what I remember from debugging Castle (although the code example should reproduce it).

The diagnostic class that writes down missing dependencies works really great, and when there **are** missing dependencies, it gives you an awful lot of detail. It this case, since the dependency is passed down as an inline argument, the diagnostic class identifies it and does not print any missing dependency information - **there is nothing missing**! :) (It just prints that a class cannot be instantiated because of missing dependencies and then it iterates over two types of missing dependencies, and since there are none that is the end of the output).

*Re point number 3:*

So the real problem is the calling code - the one that *thinks* dependencies are missing (all calls the diagnostic class to output information about it), when there are dependencies available.

I was able to trace it down to the classes that decide which constructor to pick. There is a ranking mechanism in place and I think that that code disregards inline dependencies somehow. It throws the candidate constructor away if there are more constructors.

The code works as expected if there is only one constructor as it bypasses the logic which looks for the best constructor to pick, and simply just tries tries to use the only one available - and succeeds because the dependency is there, passed inline.

*Sorry for the essay*

This is a long post and both this and the code example above could have probably be condensed to half its size. Hope you or whoever will end up supplying a fix for this will find it helpful though.

Best regards,
Ondrej.

**Comment by kkozmic** [comment]
Hi Ondrej

Yeah, that's clear as a day now :)

It sounds like there is some implicit dependency between some classes, that assume default implementations of certain other elements are used (as in the case of `DefaultDependencyResolver`).

I'm guessing having left the company you're no longer interested in playing with PRing a solution to that?

cheers,
Krzysztof

**Comment by fir3pho3nixx** [comment]
No PR closing
