### ISSUE TITLE
log4net dependency is still to log4net version 1.2.10 (Friday, January 07 2011)

### ISSUE THREAD

**Issue by sabbadino** [castleproject/Windsor#86]
There are a few features I'd like to use, that are present in next versions.
Any reason  why you do not upgrade the reference ?

**Comment by jonorossi** [comment]
@sabbadino see #53 and [my comments on the users mailing lists on Apr 3](https://groups.google.com/d/msg/castle-project-users/MJjhaq82ZL4/_5r3mGAkLqcJ).

tl;dr, there are breaking changes other than the strong name key.
