### ISSUE TITLE
Logging Facility does not create new ILogger per web request

### ISSUE THREAD

**Issue by workabyte** [castleproject/Windsor#93]
One of the items logged when using NLog is 'Count'. Simple way for us to watch the call progression on a given thread.

When using the Logging facility on our MVC applications we are seeing that the Count is not resetting per web request and will continue to increment until IIS is recycled.

After digging around I can not see to find a way to have the Logging Facility create a new ILogger instance per web request. Seems like this would be a common desire. 

NOTE: Im very new to castle.windsor so if this is something simple and im just missing it them my apologies. 

I have [this questions open on SO](http://stackoverflow.com/questions/30782338/asp-mvc-castle-nlog-count-does-not-reset)

**Comment by pcKris** [comment]
was able to work around it with the following, what is lost by not using the facility?
Thanks,

```c#
        public void Install(IWindsorContainer container, IConfigurationStore store)
        {
            container.Register(
                Component
                    .For<ILoggerFactory>()
                    .ImplementedBy <NLogFactory>()
                    .DependsOn(Dependency.OnValue("configFile", "nlog.config"))
                    .LifestylePerWebRequest(),
                Component.For<ILogger>()
                    .UsingFactoryMethod(
                        (kernel, model, context) =>
                        {
                            var logger = kernel.Resolve<ILoggerFactory>()
                                .Create(context.Handler.ComponentModel.ComponentName.Name);
                            return logger;
                        })
                    .LifestyleTransient()
                );
        }
```

**Comment by dalefrancis88** [comment]
Hey,

I may be off base with what you're wanting to do, but i think you've got your lifestyles mixed up. The factory should have a singleton lifestyle and the logger should have a PerWebRequest lifestyle because it's that you want to have one per request? 

The factories lifestyle has no affect on the items it creates. Using the factory method the way you are is allowing it to work because every time it creates the transient object it is then resolving a new factory if it's a new request.

    container.Register(
                    Component
                        .For<ILoggerFactory>()
                        .ImplementedBy <NLogFactory>()
                        .DependsOn(Dependency.OnValue("configFile", "nlog.config")),
                    Component.For<ILogger>()
                        .ImplementedBy <NLogger>()
                        .LifestylePerWebRequest()
                    );

**Comment by pcKris** [comment]
Good point, I'll check that out. Thanks for the input. What your saying
makes sense so I'll see if it ends with the desired result and post back.

Still feel like I should be able to get a per web request logger using the
facility out of the box.

-Chris

**Comment by dalefrancis88** [comment]
Hey,

Well you will out of the box but its the service that needs the right life-style

**Comment by pcKris** [comment]
Can you give me an example?

-Chris

**Comment by dalefrancis88** [comment]
Can do, I am working on a small asp thing this week so I'll incorporate
this and send some code

**Comment by pcKris** [comment]
Ping for progress on this one

-Chris

**Comment by fir3pho3nixx** [comment]
@workabyte - please feel free to ping back on this issue, I am clearing out the backlog to keep things relevant for Castle.Windsor. 

Closing for now will ask for forgiveness later :)
