### ISSUE TITLE
ParameterKey.Eq doesn't accept a numeric value

### ISSUE THREAD

**Issue by Pajamaman** [castleproject/Windsor#97]
[This page](https://github.com/castleproject/Windsor/blob/master/docs/inline-dependencies.md#setting-up-properties-propertyforkey) has an example where a numeric value is passed to ParameterKey.Eq during fluent registration:

```c#
container.Register(
    Component.For<ICustomer>().ImplementedBy<CustomerImpl>()
        .DependsOn(Property.ForKey("Name").Eq("Caption Hook"), Property.ForKey("Age").Eq(45)));
```

When I try to use it that way I get a compiler error:

```
Cannot resolve method `Eq(int)`, candidates are:
Castle.MicroKernel.Registration.Parameter Eq(Castle.Core.Configuration.IConfiguration)
Castle.MicroKernel.Registration.Parameter Eq(string)
```

I'm not sure what should be done in this instance, otherwise I'd just update the doc myself. Probably just cast it to a string, but it seems like this may be a bug.

**Comment by jonorossi** [comment]
The example you've linked to and included use `Property.ForKey()`, which is different to `Parameter.ForKey()`. `PropertyKey.Eq(object value)` is the signature for `Property`.

`Property` is an `object`/`object` key/value pair, while `Parameter` is used when reading out of a configuration and that can only be a string or an `IConfiguration`, and must be a string key.

**Comment by Pajamaman** [comment]
Oh, *Parameter* not *Property*. My bad.
