### ISSUE TITLE
memory leak using typed factory facility

### ISSUE THREAD

**Issue by ktam33** [castleproject/Windsor#98]
The following code snippet leads to a memory leak due to dynamically loaded assemblies that are not cleaned up. The performance monitor counter [.NET Clr Loading -> Current Assemblies] can be used to see the issue. 

While the usage of Windsor here is not ideal (repeated instantiation of the container), it should probably still be able to clean up after itself properly. 

There has been some discussion of this issue here as well: http://stackoverflow.com/questions/14731058/castle-windsor-interceptor-memory-leak

```
class Program
{
    static void Main(string[] args)
    {
        while (true)
        {
            using (var container = new WindsorContainer())
            {
                container.Kernel.AddFacility<TypedFactoryFacility>();
                container.Register(Component.For<IMyFactory>().AsFactory());

                var myComponent = container.Resolve<IMyFactory>();
                container.Release(myComponent); 
            }
        }
    }
}
public interface IMyFactory{}
```

**Comment by fir3pho3nixx** [comment]
We are thinking of deprecating this facility. Please join the discussion on https://github.com/castleproject/Windsor/issues/339

**Comment by jonorossi** [comment]
Reopening, we are looking removing the deprecated factory support facility, not the typed factory facility.

**Comment by jonorossi** [comment]
> The following code snippet leads to a memory leak due to dynamically loaded assemblies that are not cleaned up.

It actually can't, the CLR does not permit unloading an assembly once it is loaded and each instance of the typed factory facility doesn't know what another instance created in the past execution of your process for that registered service.

Why are you recreating the container in your application?
